package com.heptathlon.heptathlonrmi.ServeurCentral;

import com.heptathlon.heptathlonrmi.Objets.Article;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.rmi.server.UnicastRemoteObject;
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.ThreadLocalRandom;

/**
 *
 * @author Josselin
 */
public class AccueilServeurCentral extends javax.swing.JFrame {
    boolean allume = false; // Serveur Central allumé ?
    ImplSC obj = new ImplSC();
    HelloSC stub = null;
    
    public AccueilServeurCentral() { 
        initComponents();   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialog_modif_prix_sc = new javax.swing.JDialog();
        Label_Modif_Ref = new javax.swing.JLabel();
        Label_Modif_NVprix = new javax.swing.JLabel();
        TF_Modif_ref = new javax.swing.JTextField();
        TF_Modif_NVprix = new javax.swing.JTextField();
        boutonValiderModif = new javax.swing.JButton();
        dialog_suppr_article_sc = new javax.swing.JDialog();
        Label_Suppression_Reference1 = new javax.swing.JLabel();
        TF_Suppression_Reference1 = new javax.swing.JTextField();
        boutonValiderSuppression1 = new javax.swing.JButton();
        dialog_modif_stock_sc = new javax.swing.JDialog();
        Label_Modif_Ref_Stock = new javax.swing.JLabel();
        Label_Modif_Stock = new javax.swing.JLabel();
        TF_Modif_ref_stock = new javax.swing.JTextField();
        TF_Modif_NVstock = new javax.swing.JTextField();
        boutonValiderModifStock = new javax.swing.JButton();
        btn_start_central = new javax.swing.JButton();
        Label_Ajout_Famille = new javax.swing.JLabel();
        TF_Ajout_famille = new javax.swing.JTextField();
        TF_Ajout_nom = new javax.swing.JTextField();
        TF_Ajout_prixUnitaire = new javax.swing.JTextField();
        TF_Ajout_stock = new javax.swing.JTextField();
        boutonValiderAjout = new javax.swing.JButton();
        Label_Ajout_stock = new javax.swing.JLabel();
        Label_Ajout_Nom = new javax.swing.JLabel();
        Label_Ajout_PU = new javax.swing.JLabel();
        btn_visu_sc = new javax.swing.JButton();
        btn_modif_prix_sc = new javax.swing.JButton();
        btn_suppr_sc = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        Liste_article_sc = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        dialog_modif_prix_sc.setTitle("Modifier article");
        dialog_modif_prix_sc.setAlwaysOnTop(true);
        dialog_modif_prix_sc.setLocation(new java.awt.Point(150, 150));
        dialog_modif_prix_sc.setResizable(false);
        dialog_modif_prix_sc.setSize(new java.awt.Dimension(450, 450));

        Label_Modif_Ref.setText("Référence");
        Label_Modif_Ref.setMaximumSize(new java.awt.Dimension(450, 450));

        Label_Modif_NVprix.setText("Nouveau prix");
        Label_Modif_NVprix.setMaximumSize(new java.awt.Dimension(450, 450));

        TF_Modif_ref.setToolTipText("");
        TF_Modif_ref.setMaximumSize(new java.awt.Dimension(450, 450));

        TF_Modif_NVprix.setToolTipText("");
        TF_Modif_NVprix.setMaximumSize(new java.awt.Dimension(450, 450));

        boutonValiderModif.setText("Valider");
        boutonValiderModif.setToolTipText("");
        boutonValiderModif.setMaximumSize(new java.awt.Dimension(450, 450));
        boutonValiderModif.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boutonValiderModifMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout dialog_modif_prix_scLayout = new javax.swing.GroupLayout(dialog_modif_prix_sc.getContentPane());
        dialog_modif_prix_sc.getContentPane().setLayout(dialog_modif_prix_scLayout);
        dialog_modif_prix_scLayout.setHorizontalGroup(
            dialog_modif_prix_scLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialog_modif_prix_scLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(dialog_modif_prix_scLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label_Modif_Ref, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Label_Modif_NVprix, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(48, 48, 48)
                .addGroup(dialog_modif_prix_scLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TF_Modif_ref, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TF_Modif_NVprix, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(boutonValiderModif, javax.swing.GroupLayout.PREFERRED_SIZE, 81, Short.MAX_VALUE))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        dialog_modif_prix_scLayout.setVerticalGroup(
            dialog_modif_prix_scLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialog_modif_prix_scLayout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(dialog_modif_prix_scLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TF_Modif_ref, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_Modif_Ref, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dialog_modif_prix_scLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_Modif_NVprix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TF_Modif_NVprix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addComponent(boutonValiderModif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(162, Short.MAX_VALUE))
        );

        dialog_suppr_article_sc.setTitle("Supprimer article");
        dialog_suppr_article_sc.setAlwaysOnTop(true);
        dialog_suppr_article_sc.setLocation(new java.awt.Point(150, 150));
        dialog_suppr_article_sc.setResizable(false);
        dialog_suppr_article_sc.setSize(new java.awt.Dimension(450, 450));

        Label_Suppression_Reference1.setText("Référence");
        Label_Suppression_Reference1.setMaximumSize(new java.awt.Dimension(450, 450));

        TF_Suppression_Reference1.setToolTipText("");
        TF_Suppression_Reference1.setMaximumSize(new java.awt.Dimension(450, 450));

        boutonValiderSuppression1.setText("Valider");
        boutonValiderSuppression1.setToolTipText("");
        boutonValiderSuppression1.setMaximumSize(new java.awt.Dimension(450, 450));
        boutonValiderSuppression1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boutonValiderSuppression1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout dialog_suppr_article_scLayout = new javax.swing.GroupLayout(dialog_suppr_article_sc.getContentPane());
        dialog_suppr_article_sc.getContentPane().setLayout(dialog_suppr_article_scLayout);
        dialog_suppr_article_scLayout.setHorizontalGroup(
            dialog_suppr_article_scLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialog_suppr_article_scLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(Label_Suppression_Reference1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dialog_suppr_article_scLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(boutonValiderSuppression1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, Short.MAX_VALUE)
                    .addComponent(TF_Suppression_Reference1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        dialog_suppr_article_scLayout.setVerticalGroup(
            dialog_suppr_article_scLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialog_suppr_article_scLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(dialog_suppr_article_scLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TF_Suppression_Reference1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_Suppression_Reference1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(boutonValiderSuppression1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        dialog_modif_stock_sc.setSize(new java.awt.Dimension(450, 450));

        Label_Modif_Ref_Stock.setText("Référence");
        Label_Modif_Ref_Stock.setMaximumSize(new java.awt.Dimension(450, 450));

        Label_Modif_Stock.setText("Nouveau stock");
        Label_Modif_Stock.setMaximumSize(new java.awt.Dimension(450, 450));

        TF_Modif_ref_stock.setToolTipText("");
        TF_Modif_ref_stock.setMaximumSize(new java.awt.Dimension(450, 450));

        TF_Modif_NVstock.setToolTipText("");
        TF_Modif_NVstock.setMaximumSize(new java.awt.Dimension(450, 450));

        boutonValiderModifStock.setText("Valider");
        boutonValiderModifStock.setToolTipText("");
        boutonValiderModifStock.setMaximumSize(new java.awt.Dimension(450, 450));
        boutonValiderModifStock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boutonValiderModifStockMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout dialog_modif_stock_scLayout = new javax.swing.GroupLayout(dialog_modif_stock_sc.getContentPane());
        dialog_modif_stock_sc.getContentPane().setLayout(dialog_modif_stock_scLayout);
        dialog_modif_stock_scLayout.setHorizontalGroup(
            dialog_modif_stock_scLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialog_modif_stock_scLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(dialog_modif_stock_scLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label_Modif_Ref_Stock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Label_Modif_Stock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(48, 48, 48)
                .addGroup(dialog_modif_stock_scLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TF_Modif_ref_stock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TF_Modif_NVstock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(boutonValiderModifStock, javax.swing.GroupLayout.PREFERRED_SIZE, 81, Short.MAX_VALUE))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        dialog_modif_stock_scLayout.setVerticalGroup(
            dialog_modif_stock_scLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialog_modif_stock_scLayout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(dialog_modif_stock_scLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TF_Modif_ref_stock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_Modif_Ref_Stock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dialog_modif_stock_scLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_Modif_Stock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TF_Modif_NVstock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addComponent(boutonValiderModifStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(156, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_start_central.setText("Start");
        btn_start_central.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_start_centralMouseClicked(evt);
            }
        });

        Label_Ajout_Famille.setText("Famille : ");
        Label_Ajout_Famille.setMaximumSize(new java.awt.Dimension(450, 450));

        TF_Ajout_famille.setToolTipText("");
        TF_Ajout_famille.setMaximumSize(new java.awt.Dimension(450, 450));

        TF_Ajout_nom.setToolTipText("");
        TF_Ajout_nom.setMaximumSize(new java.awt.Dimension(450, 450));

        TF_Ajout_prixUnitaire.setToolTipText("");
        TF_Ajout_prixUnitaire.setMaximumSize(new java.awt.Dimension(450, 450));

        TF_Ajout_stock.setToolTipText("");
        TF_Ajout_stock.setMaximumSize(new java.awt.Dimension(450, 450));

        boutonValiderAjout.setText("Nouvelle article");
        boutonValiderAjout.setToolTipText("");
        boutonValiderAjout.setMaximumSize(new java.awt.Dimension(450, 450));
        boutonValiderAjout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boutonValiderAjoutMouseClicked(evt);
            }
        });

        Label_Ajout_stock.setText("Stock :");
        Label_Ajout_stock.setMaximumSize(new java.awt.Dimension(450, 450));

        Label_Ajout_Nom.setText("Nom :");
        Label_Ajout_Nom.setMaximumSize(new java.awt.Dimension(450, 450));

        Label_Ajout_PU.setText("Prix unitaire :");
        Label_Ajout_PU.setMaximumSize(new java.awt.Dimension(450, 450));

        btn_visu_sc.setText("Visualiser stock");
        btn_visu_sc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_visu_scMouseClicked(evt);
            }
        });

        btn_modif_prix_sc.setText("Modifier prix");
        btn_modif_prix_sc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_modif_prix_scMouseClicked(evt);
            }
        });
        btn_modif_prix_sc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modif_prix_scActionPerformed(evt);
            }
        });

        btn_suppr_sc.setText("Supprimer article");
        btn_suppr_sc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_suppr_scMouseClicked(evt);
            }
        });

        Liste_article_sc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Reference", "Famille", "Nom", "Prix unitaire", "Stock"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(Liste_article_sc);
        if (Liste_article_sc.getColumnModel().getColumnCount() > 0) {
            Liste_article_sc.getColumnModel().getColumn(0).setResizable(false);
            Liste_article_sc.getColumnModel().getColumn(1).setResizable(false);
            Liste_article_sc.getColumnModel().getColumn(2).setResizable(false);
            Liste_article_sc.getColumnModel().getColumn(3).setResizable(false);
            Liste_article_sc.getColumnModel().getColumn(4).setResizable(false);
        }

        jButton1.setText("Modifier stock");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_modif_stock(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(btn_start_central)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Label_Ajout_Famille, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Label_Ajout_Nom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Label_Ajout_PU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Label_Ajout_stock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_suppr_sc, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btn_modif_prix_sc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_visu_sc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TF_Ajout_nom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TF_Ajout_famille, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TF_Ajout_prixUnitaire, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TF_Ajout_stock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(boutonValiderAjout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(45, 45, 45)))
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(btn_start_central)
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Label_Ajout_Famille, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TF_Ajout_famille, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TF_Ajout_nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Label_Ajout_Nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Label_Ajout_PU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TF_Ajout_prixUnitaire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Label_Ajout_stock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TF_Ajout_stock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boutonValiderAjout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_visu_sc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_modif_prix_sc)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_suppr_sc)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void start() {
        if (!allume) {
            try {
                stub = (HelloSC) UnicastRemoteObject.exportObject((HelloSC) obj, 0);
                Registry registry = null;
                registry = LocateRegistry.createRegistry(ThreadLocalRandom.current().nextInt(2000, 30000 + 1));
                registry.rebind("HelloSC", stub);
                allume = true;
            } catch (Exception e) {
                e.printStackTrace();
            }
            Label_Ajout_Famille.setVisible(true);
            Label_Ajout_stock.setVisible(true);
            Label_Ajout_Nom.setVisible(true);
            Label_Ajout_PU.setVisible(true);
            TF_Ajout_famille.setVisible(true);
            TF_Ajout_nom.setVisible(true);
            TF_Ajout_prixUnitaire.setVisible(true);
            TF_Ajout_stock.setVisible(true);
            boutonValiderAjout.setVisible(true);
            boutonValiderAjout.setText("Ajouter"); 
            showArticles();
        } 
    }
    
    private void showArticles() {
        try {
            int i = 0;
            List<Article> list = new ArrayList();
            list = stub.getArticles();
            for (Article s:list) {   
                Liste_article_sc.setValueAt(s.getReference(), i, 0);
                Liste_article_sc.setValueAt(s.getFamille(), i,1);
                Liste_article_sc.setValueAt(s.getNom(), i, 2);
                Liste_article_sc.setValueAt(s.getPrix_unitaire(), i, 3);
                Liste_article_sc.setValueAt(s.getNb_stock(), i, 4);
                i++;                  
            } 
            Liste_article_sc.setValueAt(null,i,0);  
            Liste_article_sc.setValueAt("", i,1);
            Liste_article_sc.setValueAt("", i,2);
            Liste_article_sc.setValueAt(null, i,3);
            Liste_article_sc.setValueAt(null, i,4);
        }catch(Exception e) {
            e.printStackTrace();
        }
    }
    
    private void reset() {
        TF_Ajout_famille.setText("");
        TF_Ajout_nom.setText("");
        TF_Ajout_prixUnitaire.setText("");
        TF_Ajout_stock.setText("");
    }
    
    private boolean syntaxe(String type, String valeur) {
        if ("prix".equals(type)) {
            try {
                String st = valeur.replace(",", ".");
                double test = (Double.parseDouble(st));
            }catch(Exception e) {
                return false;
            }
        }
        if ("int".equals(type)) {
            try {
                int test = (Integer.parseInt(valeur));
            }catch(Exception e) {
                return false;
            }
        }
        return true;
    }
    //BOUTON START SC
    private void btn_start_centralMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_start_centralMouseClicked
        start();
    }//GEN-LAST:event_btn_start_centralMouseClicked

    //BOUTON VALIDER AJOUT STOCK
    private void boutonValiderAjoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boutonValiderAjoutMouseClicked
        //start();
        if ("".equals(TF_Ajout_famille.getText()) || "".equals(TF_Ajout_nom.getText()) || "".equals(TF_Ajout_prixUnitaire.getText()) ||
                "".equals(TF_Ajout_stock.getText())){
            boutonValiderAjout.setText("Données manquantes");
        } else {
            try {
                String famille = TF_Ajout_famille.getText();
                String nom = TF_Ajout_nom.getText();
                if (!syntaxe("prix", TF_Ajout_prixUnitaire.getText())) {
                    boutonValiderAjout.setText("Mauvais prix");
                }
                if (!syntaxe("int", TF_Ajout_stock.getText())) {
                    boutonValiderAjout.setText("Mauvais stock");
                }
                double prix = Double.parseDouble(TF_Ajout_prixUnitaire.getText().replace(",", "."));
                int stock = Integer.parseInt(TF_Ajout_stock.getText());
                
                stub.addArticle(famille, nom, prix, stock);
                boutonValiderAjout.setText("Ajouter");
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        reset();
        showArticles();
    }//GEN-LAST:event_boutonValiderAjoutMouseClicked

    //BOUTON VISUALISER STOCKS
    private void btn_visu_scMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_visu_scMouseClicked
        //start();
        showArticles();
    }//GEN-LAST:event_btn_visu_scMouseClicked

    //BOUTON INTERFACE MODIFIER PRIX
    private void btn_modif_prix_scMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_modif_prix_scMouseClicked
        //start();
        dialog_modif_prix_sc.setVisible(true);
        TF_Modif_ref.setText("");
        TF_Modif_NVprix.setText("");
    }//GEN-LAST:event_btn_modif_prix_scMouseClicked

    //BOUTON VALIDER MODIFIER PRIX
    private void boutonValiderModifMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boutonValiderModifMouseClicked
        //start();
        if ("".equals(TF_Modif_ref.getText()) || "".equals(TF_Modif_ref.getText())){
            boutonValiderModif.setText("Données manquantes"); 
        } else {
            try {
                String ref = TF_Modif_ref.getText();
                String prix = TF_Modif_NVprix.getText();
                stub.updateArticle(ref, prix, "prix_unitaire");
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        reset();
        showArticles();
    }//GEN-LAST:event_boutonValiderModifMouseClicked

    //BOUTON SUPPRIMER ARTICLE
    private void boutonValiderSuppression1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boutonValiderSuppression1MouseClicked
        //start();
        if ("".equals(TF_Suppression_Reference1.getText())){
            boutonValiderSuppression1.setText("Données manquantes");
        } else {
            try {
                String ref = TF_Suppression_Reference1.getText();
                stub.deleteArticle(ref);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }     
        showArticles();
    }//GEN-LAST:event_boutonValiderSuppression1MouseClicked

    //BOUTON INTERFACE SUPPRIMER
    private void btn_suppr_scMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_suppr_scMouseClicked
        //start();
        dialog_suppr_article_sc.setVisible(true);
    }//GEN-LAST:event_btn_suppr_scMouseClicked

    private void btn_modif_prix_scActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modif_prix_scActionPerformed

    }//GEN-LAST:event_btn_modif_prix_scActionPerformed

    private void btn_modif_stock(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_modif_stock
        dialog_modif_stock_sc.setVisible(true);
    }//GEN-LAST:event_btn_modif_stock

    private void boutonValiderModifStockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boutonValiderModifStockMouseClicked
        //start();
        if ("".equals(TF_Modif_ref_stock.getText()) || "".equals(TF_Modif_ref_stock.getText())){
            boutonValiderModifStock.setText("Données manquantes"); 
        } else {
            try {
                String ref = TF_Modif_ref_stock.getText();
                String stock = TF_Modif_NVstock.getText();
                stub.updateArticle(ref, stock, "nb_stock");
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        reset();
        showArticles();
    }//GEN-LAST:event_boutonValiderModifStockMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccueilServeurCentral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccueilServeurCentral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccueilServeurCentral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccueilServeurCentral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AccueilServeurCentral().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label_Ajout_Famille;
    private javax.swing.JLabel Label_Ajout_Nom;
    private javax.swing.JLabel Label_Ajout_PU;
    private javax.swing.JLabel Label_Ajout_stock;
    private javax.swing.JLabel Label_Modif_NVprix;
    private javax.swing.JLabel Label_Modif_Ref;
    private javax.swing.JLabel Label_Modif_Ref_Stock;
    private javax.swing.JLabel Label_Modif_Stock;
    private javax.swing.JLabel Label_Suppression_Reference1;
    private javax.swing.JTable Liste_article_sc;
    private javax.swing.JTextField TF_Ajout_famille;
    private javax.swing.JTextField TF_Ajout_nom;
    private javax.swing.JTextField TF_Ajout_prixUnitaire;
    private javax.swing.JTextField TF_Ajout_stock;
    private javax.swing.JTextField TF_Modif_NVprix;
    private javax.swing.JTextField TF_Modif_NVstock;
    private javax.swing.JTextField TF_Modif_ref;
    private javax.swing.JTextField TF_Modif_ref_stock;
    private javax.swing.JTextField TF_Suppression_Reference1;
    private javax.swing.JButton boutonValiderAjout;
    private javax.swing.JButton boutonValiderModif;
    private javax.swing.JButton boutonValiderModifStock;
    private javax.swing.JButton boutonValiderSuppression1;
    private javax.swing.JButton btn_modif_prix_sc;
    private javax.swing.JButton btn_start_central;
    private javax.swing.JButton btn_suppr_sc;
    private javax.swing.JButton btn_visu_sc;
    private javax.swing.JDialog dialog_modif_prix_sc;
    private javax.swing.JDialog dialog_modif_stock_sc;
    private javax.swing.JDialog dialog_suppr_article_sc;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
