package com.heptathlon.heptathlonrmi;

import com.heptathlon.heptathlonrmi.Objets.Facture;
import com.heptathlon.heptathlonrmi.Objets.Article;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.rmi.server.UnicastRemoteObject;
import java.text.DateFormat;
import java.text.SimpleDateFormat;

import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.concurrent.ThreadLocalRandom;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;


public class AccueilCaisse extends javax.swing.JFrame {

    int i = 0;
    int nb_ligne_visualiser = 57;   
    double montantTotal = 0;
    double montantFacture = 0;
 
    public AccueilCaisse() {
        initComponents();
    }
    
    public Object[][] getTableData (JTable table) {
        
        DefaultTableModel dtm = (DefaultTableModel) table.getModel();
        int nRow = dtm.getRowCount(), nCol = dtm.getColumnCount();
        Object[][] tableData = new Object[nRow][nCol];
        for (int i = 0 ; i < nRow ; i++)
            for (int j = 0 ; j < nCol ; j++)
                tableData[i][j] = dtm.getValueAt(i,j);
        
        return tableData;
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ConsultationRef = new javax.swing.JDialog();
        Label_Consult_Ref = new javax.swing.JLabel();
        TF_Consult_Ref = new javax.swing.JTextField();
        boutonValiderConsult = new javax.swing.JButton();
        ConsultationFamille = new javax.swing.JDialog();
        Label_Consult_Famille = new javax.swing.JLabel();
        TF_Consult_Famille = new javax.swing.JTextField();
        boutonValiderFamille = new javax.swing.JButton();
        CreationFacture = new javax.swing.JDialog();
        boutonCreerFacture = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Liste_PreFacture = new javax.swing.JTable();
        TF_Montant_total = new javax.swing.JTextField();
        btn_Fact_add_line = new javax.swing.JButton();
        Label_numero_facture = new javax.swing.JLabel();
        Label_erreur_stock = new javax.swing.JLabel();
        AjoutArtFactDialog = new javax.swing.JDialog();
        Label_ajout_art_ref_fact = new javax.swing.JLabel();
        TF_ref_art_fact = new javax.swing.JTextField();
        btn_ajout_ligne_fact = new javax.swing.JButton();
        TF_qte_art_fact = new javax.swing.JTextField();
        Label_ajout_art_qte_fact = new javax.swing.JLabel();
        Label_stock_insuffisant = new javax.swing.JLabel();
        ConsultationFactureDialog = new javax.swing.JDialog();
        Label_Consult_Facture = new javax.swing.JLabel();
        TF_Consult_Facture = new javax.swing.JTextField();
        boutonValiderRechercheFacture = new javax.swing.JButton();
        Resultat_recherche_facture = new javax.swing.JDialog();
        liste_facture = new javax.swing.JScrollPane();
        Liste_resultat_recherche_fact = new javax.swing.JTable();
        TF_Montant_total_Consult_Fact = new javax.swing.JTextField();
        btn_paiement_fact = new javax.swing.JButton();
        Label_Fact_numero = new javax.swing.JLabel();
        Radio_btn_CB = new javax.swing.JRadioButton();
        Radio_btn_especes = new javax.swing.JRadioButton();
        Radio_btn_autres = new javax.swing.JRadioButton();
        TicketCaisse_Dialog = new javax.swing.JDialog();
        setVisible(false);
        Label_ValiderAjout1 = new javax.swing.JLabel();
        Squelette1 = new javax.swing.JLabel();
        Squelette2 = new javax.swing.JLabel();
        liste_facture1 = new javax.swing.JScrollPane();
        Liste_resultat_recherche_fact1 = new javax.swing.JTable();
        TF_Montant_total_Consult_Fact1 = new javax.swing.JTextField();
        Calcul_CA_Dialog = new javax.swing.JDialog();
        Label_date_CA_debut = new javax.swing.JLabel();
        btn_calculerCA = new javax.swing.JButton();
        Label_date_CA_fin = new javax.swing.JLabel();
        Label_CA_Total = new javax.swing.JLabel();
        dateDebut = new org.jdesktop.swingx.JXDatePicker();
        dateFin = new org.jdesktop.swingx.JXDatePicker();
        btn_visualiser_art = new javax.swing.JButton();
        btn_quit = new javax.swing.JButton();
        Tableau_articles = new javax.swing.JScrollPane();
        liste_articles = new javax.swing.JTable();
        btn_consultRef = new javax.swing.JButton();
        btn_consultFamille = new javax.swing.JButton();
        btn_consultFact = new javax.swing.JButton();
        btn_creaFact = new javax.swing.JButton();
        btn_CA = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        ConsultationRef.setTitle("Consultation par référence");
        ConsultationRef.setAlwaysOnTop(true);
        ConsultationRef.setLocation(new java.awt.Point(150, 150));
        ConsultationRef.setResizable(false);
        ConsultationRef.setSize(new java.awt.Dimension(450, 450));

        Label_Consult_Ref.setText("Recherche par référence");
        Label_Consult_Ref.setMaximumSize(new java.awt.Dimension(450, 450));

        TF_Consult_Ref.setToolTipText("");
        TF_Consult_Ref.setMaximumSize(new java.awt.Dimension(450, 450));

        boutonValiderConsult.setText("Valider");
        boutonValiderConsult.setToolTipText("");
        boutonValiderConsult.setMaximumSize(new java.awt.Dimension(450, 450));
        boutonValiderConsult.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boutonValiderConsultMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ConsultationRefLayout = new javax.swing.GroupLayout(ConsultationRef.getContentPane());
        ConsultationRef.getContentPane().setLayout(ConsultationRefLayout);
        ConsultationRefLayout.setHorizontalGroup(
            ConsultationRefLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConsultationRefLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(Label_Consult_Ref, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(ConsultationRefLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(boutonValiderConsult, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                    .addComponent(TF_Consult_Ref, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        ConsultationRefLayout.setVerticalGroup(
            ConsultationRefLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConsultationRefLayout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(ConsultationRefLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TF_Consult_Ref, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_Consult_Ref, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(boutonValiderConsult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        ConsultationFamille.setTitle("Consultation par famille");
        ConsultationFamille.setAlwaysOnTop(true);
        ConsultationFamille.setLocation(new java.awt.Point(150, 150));
        ConsultationFamille.setResizable(false);
        ConsultationFamille.setSize(new java.awt.Dimension(450, 450));

        Label_Consult_Famille.setText("Recherche par famille");
        Label_Consult_Famille.setMaximumSize(new java.awt.Dimension(450, 450));

        TF_Consult_Famille.setToolTipText("");
        TF_Consult_Famille.setMaximumSize(new java.awt.Dimension(450, 450));

        boutonValiderFamille.setText("Valider");
        boutonValiderFamille.setToolTipText("");
        boutonValiderFamille.setMaximumSize(new java.awt.Dimension(450, 450));
        boutonValiderFamille.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boutonValiderFamilleMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ConsultationFamilleLayout = new javax.swing.GroupLayout(ConsultationFamille.getContentPane());
        ConsultationFamille.getContentPane().setLayout(ConsultationFamilleLayout);
        ConsultationFamilleLayout.setHorizontalGroup(
            ConsultationFamilleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConsultationFamilleLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(Label_Consult_Famille, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(ConsultationFamilleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(boutonValiderFamille, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                    .addComponent(TF_Consult_Famille, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        ConsultationFamilleLayout.setVerticalGroup(
            ConsultationFamilleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConsultationFamilleLayout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(ConsultationFamilleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TF_Consult_Famille, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_Consult_Famille, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(boutonValiderFamille, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        CreationFacture.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        CreationFacture.setTitle("Pre - facture");
        CreationFacture.setAlwaysOnTop(true);
        CreationFacture.setLocation(new java.awt.Point(150, 150));
        CreationFacture.setResizable(false);
        CreationFacture.setSize(new java.awt.Dimension(450, 450));

        boutonCreerFacture.setText("Créer facture");
        boutonCreerFacture.setToolTipText("");
        boutonCreerFacture.setMaximumSize(new java.awt.Dimension(450, 450));
        boutonCreerFacture.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boutonCreerFactureMouseClicked(evt);
            }
        });

        Liste_PreFacture.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Référence article", "Famille", "Nom", "Quantité", "PU", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Liste_PreFacture.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(Liste_PreFacture);
        if (Liste_PreFacture.getColumnModel().getColumnCount() > 0) {
            Liste_PreFacture.getColumnModel().getColumn(0).setResizable(false);
            Liste_PreFacture.getColumnModel().getColumn(1).setResizable(false);
            Liste_PreFacture.getColumnModel().getColumn(2).setResizable(false);
            Liste_PreFacture.getColumnModel().getColumn(3).setResizable(false);
            Liste_PreFacture.getColumnModel().getColumn(4).setResizable(false);
            Liste_PreFacture.getColumnModel().getColumn(5).setResizable(false);
        }

        TF_Montant_total.setText("Montant total");

        btn_Fact_add_line.setText("Ajouter article");
        btn_Fact_add_line.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_Fact_add_lineMouseClicked(evt);
            }
        });

        Label_numero_facture.setText("Numéro facture");
        Label_numero_facture.setToolTipText("");

        javax.swing.GroupLayout CreationFactureLayout = new javax.swing.GroupLayout(CreationFacture.getContentPane());
        CreationFacture.getContentPane().setLayout(CreationFactureLayout);
        CreationFactureLayout.setHorizontalGroup(
            CreationFactureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreationFactureLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CreationFactureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CreationFactureLayout.createSequentialGroup()
                        .addComponent(btn_Fact_add_line, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CreationFactureLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Label_numero_facture, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(99, 99, 99)
                        .addComponent(TF_Montant_total, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 819, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CreationFactureLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Label_erreur_stock)
                .addGap(228, 228, 228))
            .addGroup(CreationFactureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CreationFactureLayout.createSequentialGroup()
                    .addContainerGap(679, Short.MAX_VALUE)
                    .addComponent(boutonCreerFacture, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(19, 19, 19)))
        );
        CreationFactureLayout.setVerticalGroup(
            CreationFactureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreationFactureLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_Fact_add_line, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(CreationFactureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Label_numero_facture, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TF_Montant_total))
                .addGap(53, 53, 53)
                .addComponent(Label_erreur_stock)
                .addGap(32, 32, 32))
            .addGroup(CreationFactureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CreationFactureLayout.createSequentialGroup()
                    .addContainerGap(417, Short.MAX_VALUE)
                    .addComponent(boutonCreerFacture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(30, 30, 30)))
        );

        AjoutArtFactDialog.setTitle("Ajout article pour pre - facture");
        AjoutArtFactDialog.setAlwaysOnTop(true);
        AjoutArtFactDialog.setLocation(new java.awt.Point(150, 150));
        AjoutArtFactDialog.setResizable(false);
        AjoutArtFactDialog.setSize(new java.awt.Dimension(450, 450));

        Label_ajout_art_ref_fact.setText("Référence");
        Label_ajout_art_ref_fact.setMaximumSize(new java.awt.Dimension(450, 450));

        TF_ref_art_fact.setToolTipText("");
        TF_ref_art_fact.setMaximumSize(new java.awt.Dimension(450, 450));

        btn_ajout_ligne_fact.setText("Ajouter");
        btn_ajout_ligne_fact.setToolTipText("");
        btn_ajout_ligne_fact.setMaximumSize(new java.awt.Dimension(450, 450));
        btn_ajout_ligne_fact.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ajout_ligne_factMouseClicked(evt);
            }
        });

        TF_qte_art_fact.setToolTipText("");
        TF_qte_art_fact.setMaximumSize(new java.awt.Dimension(450, 450));

        Label_ajout_art_qte_fact.setText("Quantité");
        Label_ajout_art_qte_fact.setMaximumSize(new java.awt.Dimension(450, 450));

        javax.swing.GroupLayout AjoutArtFactDialogLayout = new javax.swing.GroupLayout(AjoutArtFactDialog.getContentPane());
        AjoutArtFactDialog.getContentPane().setLayout(AjoutArtFactDialogLayout);
        AjoutArtFactDialogLayout.setHorizontalGroup(
            AjoutArtFactDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AjoutArtFactDialogLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(AjoutArtFactDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label_ajout_art_ref_fact, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                    .addComponent(Label_ajout_art_qte_fact, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AjoutArtFactDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TF_qte_art_fact, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                    .addComponent(TF_ref_art_fact, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE))
                .addGap(105, 105, 105))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AjoutArtFactDialogLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_ajout_ligne_fact, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91))
            .addGroup(AjoutArtFactDialogLayout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(Label_stock_insuffisant, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AjoutArtFactDialogLayout.setVerticalGroup(
            AjoutArtFactDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AjoutArtFactDialogLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(AjoutArtFactDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TF_ref_art_fact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_ajout_art_ref_fact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AjoutArtFactDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_ajout_art_qte_fact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TF_qte_art_fact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label_stock_insuffisant, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_ajout_ligne_fact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        ConsultationFactureDialog.setTitle("Consultation facture");
        ConsultationFactureDialog.setAlwaysOnTop(true);
        ConsultationFactureDialog.setLocation(new java.awt.Point(150, 150));
        ConsultationFactureDialog.setResizable(false);
        ConsultationFactureDialog.setSize(new java.awt.Dimension(450, 450));

        Label_Consult_Facture.setText("Recherche par facture");
        Label_Consult_Facture.setMaximumSize(new java.awt.Dimension(450, 450));

        TF_Consult_Facture.setToolTipText("");
        TF_Consult_Facture.setMaximumSize(new java.awt.Dimension(450, 450));

        boutonValiderRechercheFacture.setText("Valider");
        boutonValiderRechercheFacture.setToolTipText("");
        boutonValiderRechercheFacture.setMaximumSize(new java.awt.Dimension(450, 450));
        boutonValiderRechercheFacture.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boutonValiderRechercheFactureMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ConsultationFactureDialogLayout = new javax.swing.GroupLayout(ConsultationFactureDialog.getContentPane());
        ConsultationFactureDialog.getContentPane().setLayout(ConsultationFactureDialogLayout);
        ConsultationFactureDialogLayout.setHorizontalGroup(
            ConsultationFactureDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConsultationFactureDialogLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(Label_Consult_Facture, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(ConsultationFactureDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(boutonValiderRechercheFacture, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                    .addComponent(TF_Consult_Facture, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        ConsultationFactureDialogLayout.setVerticalGroup(
            ConsultationFactureDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConsultationFactureDialogLayout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(ConsultationFactureDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TF_Consult_Facture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_Consult_Facture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(boutonValiderRechercheFacture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        Resultat_recherche_facture.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        Resultat_recherche_facture.setTitle("Facture");
        Resultat_recherche_facture.setAlwaysOnTop(true);
        Resultat_recherche_facture.setLocation(new java.awt.Point(150, 150));
        Resultat_recherche_facture.setResizable(false);
        Resultat_recherche_facture.setSize(new java.awt.Dimension(950, 450));

        Liste_resultat_recherche_fact.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Référence article", "Famille", "Nom", "Quantité", "PU", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Liste_resultat_recherche_fact.getTableHeader().setReorderingAllowed(false);
        liste_facture.setViewportView(Liste_resultat_recherche_fact);
        if (Liste_resultat_recherche_fact.getColumnModel().getColumnCount() > 0) {
            Liste_resultat_recherche_fact.getColumnModel().getColumn(0).setResizable(false);
            Liste_resultat_recherche_fact.getColumnModel().getColumn(1).setResizable(false);
            Liste_resultat_recherche_fact.getColumnModel().getColumn(2).setResizable(false);
            Liste_resultat_recherche_fact.getColumnModel().getColumn(3).setResizable(false);
            Liste_resultat_recherche_fact.getColumnModel().getColumn(4).setResizable(false);
            Liste_resultat_recherche_fact.getColumnModel().getColumn(5).setResizable(false);
        }

        TF_Montant_total_Consult_Fact.setText("Montant total");

        btn_paiement_fact.setText("Payer la facture");
        btn_paiement_fact.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_paiement_factMouseClicked(evt);
            }
        });

        Label_Fact_numero.setFont(new java.awt.Font("Cantarell", 0, 36)); // NOI18N
        Label_Fact_numero.setText("Facture numéro : ");

        Radio_btn_CB.setText("CB");
        Radio_btn_CB.setName("cb"); // NOI18N

        Radio_btn_especes.setText("Especes");
        Radio_btn_especes.setName("esp"); // NOI18N
        Radio_btn_especes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Radio_btn_especesMouseClicked(evt);
            }
        });

        Radio_btn_autres.setText("Autres");
        Radio_btn_autres.setName("other"); // NOI18N

        javax.swing.GroupLayout Resultat_recherche_factureLayout = new javax.swing.GroupLayout(Resultat_recherche_facture.getContentPane());
        Resultat_recherche_facture.getContentPane().setLayout(Resultat_recherche_factureLayout);
        Resultat_recherche_factureLayout.setHorizontalGroup(
            Resultat_recherche_factureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Resultat_recherche_factureLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Resultat_recherche_factureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(liste_facture, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 920, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Resultat_recherche_factureLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(Resultat_recherche_factureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Radio_btn_especes)
                            .addComponent(Radio_btn_CB)
                            .addComponent(Radio_btn_autres))
                        .addGap(57, 57, 57)
                        .addGroup(Resultat_recherche_factureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TF_Montant_total_Consult_Fact, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                            .addComponent(btn_paiement_fact, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(Resultat_recherche_factureLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(Label_Fact_numero, javax.swing.GroupLayout.PREFERRED_SIZE, 823, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Resultat_recherche_factureLayout.setVerticalGroup(
            Resultat_recherche_factureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Resultat_recherche_factureLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(Label_Fact_numero, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                .addComponent(liste_facture, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Radio_btn_especes)
                .addGap(2, 2, 2)
                .addGroup(Resultat_recherche_factureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TF_Montant_total_Consult_Fact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Radio_btn_CB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Resultat_recherche_factureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_paiement_fact)
                    .addComponent(Radio_btn_autres))
                .addGap(44, 44, 44))
        );

        TicketCaisse_Dialog.setTitle("Ajout article");
        TicketCaisse_Dialog.setAlwaysOnTop(true);
        TicketCaisse_Dialog.setLocation(new java.awt.Point(150, 150));
        TicketCaisse_Dialog.setResizable(false);
        TicketCaisse_Dialog.setSize(new java.awt.Dimension(450, 450));

        Label_ValiderAjout1.setEnabled(false);

        Squelette1.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        Squelette1.setText("Bienvenue chez Heptathlon !");

        Squelette2.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        Squelette2.setText("Heptathlon vous remercie de votre visite ! ");

        Liste_resultat_recherche_fact1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Référence article", "Famille", "Nom", "Quantité", "PU", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Liste_resultat_recherche_fact1.getTableHeader().setReorderingAllowed(false);
        liste_facture1.setViewportView(Liste_resultat_recherche_fact1);
        if (Liste_resultat_recherche_fact1.getColumnModel().getColumnCount() > 0) {
            Liste_resultat_recherche_fact1.getColumnModel().getColumn(0).setResizable(false);
            Liste_resultat_recherche_fact1.getColumnModel().getColumn(1).setResizable(false);
            Liste_resultat_recherche_fact1.getColumnModel().getColumn(2).setResizable(false);
            Liste_resultat_recherche_fact1.getColumnModel().getColumn(3).setResizable(false);
            Liste_resultat_recherche_fact1.getColumnModel().getColumn(4).setResizable(false);
            Liste_resultat_recherche_fact1.getColumnModel().getColumn(5).setResizable(false);
        }

        TF_Montant_total_Consult_Fact1.setText("Montant total");

        javax.swing.GroupLayout TicketCaisse_DialogLayout = new javax.swing.GroupLayout(TicketCaisse_Dialog.getContentPane());
        TicketCaisse_Dialog.getContentPane().setLayout(TicketCaisse_DialogLayout);
        TicketCaisse_DialogLayout.setHorizontalGroup(
            TicketCaisse_DialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TicketCaisse_DialogLayout.createSequentialGroup()
                .addGap(196, 196, 196)
                .addComponent(Label_ValiderAjout1, javax.swing.GroupLayout.DEFAULT_SIZE, 597, Short.MAX_VALUE)
                .addGap(67, 67, 67))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TicketCaisse_DialogLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Squelette2)
                .addGap(291, 291, 291))
            .addGroup(TicketCaisse_DialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(liste_facture1, javax.swing.GroupLayout.DEFAULT_SIZE, 836, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(TicketCaisse_DialogLayout.createSequentialGroup()
                .addGap(312, 312, 312)
                .addComponent(Squelette1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(TicketCaisse_DialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(TicketCaisse_DialogLayout.createSequentialGroup()
                    .addContainerGap(705, Short.MAX_VALUE)
                    .addComponent(TF_Montant_total_Consult_Fact1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        TicketCaisse_DialogLayout.setVerticalGroup(
            TicketCaisse_DialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TicketCaisse_DialogLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(Squelette1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(liste_facture1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label_ValiderAjout1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 174, Short.MAX_VALUE)
                .addComponent(Squelette2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
            .addGroup(TicketCaisse_DialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(TicketCaisse_DialogLayout.createSequentialGroup()
                    .addGap(327, 327, 327)
                    .addComponent(TF_Montant_total_Consult_Fact1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(195, Short.MAX_VALUE)))
        );

        Calcul_CA_Dialog.setTitle("Calcul CA");
        Calcul_CA_Dialog.setAlwaysOnTop(true);
        Calcul_CA_Dialog.setLocation(new java.awt.Point(150, 150));
        Calcul_CA_Dialog.setSize(new java.awt.Dimension(878, 160));

        Label_date_CA_debut.setText("Date de début");
        Label_date_CA_debut.setMaximumSize(new java.awt.Dimension(450, 450));

        btn_calculerCA.setText("Calculer");
        btn_calculerCA.setToolTipText("");
        btn_calculerCA.setMaximumSize(new java.awt.Dimension(450, 450));
        btn_calculerCA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_calculerCAMouseClicked(evt);
            }
        });

        Label_date_CA_fin.setText("Date de fin");
        Label_date_CA_fin.setMaximumSize(new java.awt.Dimension(450, 450));

        Label_CA_Total.setText("Total CA");

        dateDebut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateDebutActionPerformed(evt);
            }
        });

        dateFin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateFinActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Calcul_CA_DialogLayout = new javax.swing.GroupLayout(Calcul_CA_Dialog.getContentPane());
        Calcul_CA_Dialog.getContentPane().setLayout(Calcul_CA_DialogLayout);
        Calcul_CA_DialogLayout.setHorizontalGroup(
            Calcul_CA_DialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Calcul_CA_DialogLayout.createSequentialGroup()
                .addGroup(Calcul_CA_DialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Calcul_CA_DialogLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(Label_date_CA_debut, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(141, 141, 141)
                        .addComponent(Label_date_CA_fin, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Calcul_CA_DialogLayout.createSequentialGroup()
                        .addGroup(Calcul_CA_DialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Calcul_CA_DialogLayout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(dateDebut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Calcul_CA_DialogLayout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addComponent(Label_CA_Total, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(69, 69, 69)
                        .addGroup(Calcul_CA_DialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dateFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Calcul_CA_DialogLayout.createSequentialGroup()
                                .addComponent(btn_calculerCA, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)))))
                .addContainerGap(263, Short.MAX_VALUE))
        );
        Calcul_CA_DialogLayout.setVerticalGroup(
            Calcul_CA_DialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Calcul_CA_DialogLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(Calcul_CA_DialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_date_CA_debut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_date_CA_fin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Calcul_CA_DialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateDebut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(Calcul_CA_DialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_calculerCA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_CA_Total))
                .addContainerGap(213, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        btn_visualiser_art.setText("Visualiser stocks");
        btn_visualiser_art.setToolTipText("");
        btn_visualiser_art.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_visualiser_artMouseClicked(evt);
            }
        });

        btn_quit.setText("Quitter");

        liste_articles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Reference", "Famille", "Nom", "Prix unitaire", "Nb stock"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        liste_articles.setColumnSelectionAllowed(true);
        liste_articles.setRowSelectionAllowed(false);
        liste_articles.getTableHeader().setReorderingAllowed(false);
        Tableau_articles.setViewportView(liste_articles);
        liste_articles.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        if (liste_articles.getColumnModel().getColumnCount() > 0) {
            liste_articles.getColumnModel().getColumn(0).setResizable(false);
            liste_articles.getColumnModel().getColumn(1).setResizable(false);
            liste_articles.getColumnModel().getColumn(2).setResizable(false);
            liste_articles.getColumnModel().getColumn(3).setResizable(false);
            liste_articles.getColumnModel().getColumn(4).setResizable(false);
        }

        btn_consultRef.setText("Consultation par référence");
        btn_consultRef.setPreferredSize(new java.awt.Dimension(119, 29));
        btn_consultRef.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_consultRefMouseClicked(evt);
            }
        });

        btn_consultFamille.setText("Consultation par famille");
        btn_consultFamille.setPreferredSize(new java.awt.Dimension(119, 29));
        btn_consultFamille.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_consultFamilleMouseClicked(evt);
            }
        });

        btn_consultFact.setText("Consultation facture");
        btn_consultFact.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_consultFactMouseClicked(evt);
            }
        });

        btn_creaFact.setText("Création facture");
        btn_creaFact.setPreferredSize(new java.awt.Dimension(119, 29));
        btn_creaFact.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_creaFactMouseClicked(evt);
            }
        });

        btn_CA.setText("Calcul CA");
        btn_CA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_CAMouseClicked(evt);
            }
        });

        jButton1.setText("facture en fin de journée ( à faire)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btn_consultRef, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                            .addComponent(btn_visualiser_art, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_consultFamille, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(Tableau_articles, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addComponent(btn_quit))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_creaFact, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_consultFact, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_CA, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(Tableau_articles, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(btn_visualiser_art)
                        .addGap(63, 63, 63)
                        .addComponent(btn_consultRef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_consultFamille, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(btn_creaFact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(btn_consultFact)
                .addGap(38, 38, 38)
                .addComponent(btn_CA)
                .addGap(36, 36, 36)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(btn_quit)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    // BOUTON VISUALISER DEPUIS ACCUEIL
    private void btn_visualiser_artMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_visualiser_artMouseClicked
        // CLIC VISUALISER STOCK depuis AccueilCaisse
        try { 
            ImplC obj = new ImplC();
            HelloC stub = (HelloC) UnicastRemoteObject.exportObject((HelloC)obj, 0);

            Registry r = LocateRegistry.createRegistry(ThreadLocalRandom.current().nextInt(2000, 30000 + 1)); 
            r.rebind("HelloC",stub);
            List<Article> list = stub.getArticles(); 
            int i=0;
            for (Article s:list) {
                liste_articles.setValueAt(s.getReference(), i,0);
                liste_articles.setValueAt(s.getFamille(), i,1);
                liste_articles.setValueAt(s.getNom(), i,2);
                liste_articles.setValueAt(s.getPrix_unitaire(), i,3);
                liste_articles.setValueAt(s.getNb_stock(), i,4);
                i++;                  
            }  
        } catch (Exception e) { 
            e.printStackTrace();
        }   
    }//GEN-LAST:event_btn_visualiser_artMouseClicked

    // BOUTON CONSULTATION PAR REFERENCE DEPUIS ACCUEIL
    private void btn_consultRefMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_consultRefMouseClicked
        ConsultationRef.setVisible(true);
        TF_Consult_Ref.setText("");
    }//GEN-LAST:event_btn_consultRefMouseClicked
  
    // BOUTON CONSULTATION PAR FAMILLE DEPUIS ACCUEIL
    private void btn_consultFamilleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_consultFamilleMouseClicked
        ConsultationFamille.setVisible(true);
        TF_Consult_Famille.setText("");      
    }//GEN-LAST:event_btn_consultFamilleMouseClicked
 
    // BOUTON CHERCHER PAR REFERENCE DEPUIS DIALOGCONSULTREFERENCE
    private void boutonValiderConsultMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boutonValiderConsultMouseClicked
        try { 
            ImplC obj = new ImplC();
            HelloC stub = (HelloC) UnicastRemoteObject.exportObject(obj,0);
            Registry registry = LocateRegistry.createRegistry(ThreadLocalRandom.current().nextInt(2000, 30000 + 1)); 
            registry.bind("HelloC", stub); 


            List<Article> listConsult = stub.getArticle("ref", TF_Consult_Ref.getText());

            int i = 0;
            for (Article s:listConsult) {   
                liste_articles.setValueAt(s.getReference(), i, 0);
                liste_articles.setValueAt(s.getFamille(), i, 1);
                liste_articles.setValueAt(s.getNom(), i, 2);
                liste_articles.setValueAt(s.getPrix_unitaire(), i, 3);
                liste_articles.setValueAt(s.getNb_stock(), i, 4);
                i++;                  
            }  
        } catch (Exception e) { 
            e.printStackTrace();
        } 
        int j = 1;
        while (j < nb_ligne_visualiser){
            liste_articles.setValueAt(null,j, 0) ;  
            liste_articles.setValueAt("", j, 1);
            liste_articles.setValueAt("", j, 2);
            liste_articles.setValueAt(null, j, 3);
            liste_articles.setValueAt(null, j, 4);
            j++;
        }
    }//GEN-LAST:event_boutonValiderConsultMouseClicked
   
    // BOUTON CHERCHER PAR FAMILLE DEPUIS DIALOGCONSULTFAMILLE
    private void boutonValiderFamilleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boutonValiderFamilleMouseClicked
        try { 
            ImplC obj = new ImplC();
            HelloC stub = (HelloC) UnicastRemoteObject.exportObject((HelloC)obj, 0);
            Registry registry = LocateRegistry.createRegistry(ThreadLocalRandom.current().nextInt(2000, 30000 + 1)); 
            registry.rebind("HelloC",stub);
            List<Article> list = stub.getArticles(); 
            
            int i=0;
            for (Article s:list) {
                liste_articles.setValueAt(s.getReference(), i, 0);
                liste_articles.setValueAt(s.getFamille(), i, 1);
                liste_articles.setValueAt(s.getNom(), i, 2);
                liste_articles.setValueAt(s.getPrix_unitaire(), i, 3);
                i++;                  
            }  
        } catch (Exception e) { 
           e.printStackTrace();
        }
        
        try { 
            ImplC obj = new ImplC();
            HelloC stub = (HelloC) UnicastRemoteObject.exportObject((HelloC)obj, 0);           
            Registry registry = LocateRegistry.createRegistry(ThreadLocalRandom.current().nextInt(2000, 30000 + 1)); 
            registry.rebind("HelloC",stub);

            String famille_saisie = TF_Consult_Famille.getText();
            String sql = "SELECT * FROM Articles WHERE famille='"+famille_saisie+"' AND nb_stock > 0;";
            List<Article> listConsult = stub.getArticle("famille", famille_saisie);
            
            int j=0;
            for (Article s:listConsult) {   
                liste_articles.setValueAt(s.getReference(), j, 0);
                liste_articles.setValueAt(s.getFamille(), j, 1);
                liste_articles.setValueAt(s.getNom(), j, 2);
                liste_articles.setValueAt(s.getPrix_unitaire(), j, 3);
                liste_articles.setValueAt(s.getNb_stock(), j, 4);
                j++;                  
            }        
            
            int length = listConsult.size();
            while ( length+1 <= nb_ligne_visualiser ){
                liste_articles.setValueAt(null,length, 0) ;  
                liste_articles.setValueAt("", length, 1);
                liste_articles.setValueAt("", length, 2);
                liste_articles.setValueAt(null, length, 3);
                liste_articles.setValueAt(null, length, 4);
                length++;
            }
        } catch (Exception e) { 
           e.printStackTrace();
        } 
    }//GEN-LAST:event_boutonValiderFamilleMouseClicked
  
    // BOUTON CREATION FACTURE DEPUIS ACCUEIL
    private void btn_creaFactMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_creaFactMouseClicked
        CreationFacture.setVisible(true);    
    }//GEN-LAST:event_btn_creaFactMouseClicked
   
    // BOUTON CREER FACTURE DEPUIS CREER FACTURE DIALOG
    private void boutonCreerFactureMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boutonCreerFactureMouseClicked
        try { 
            System.out.println("1");
            ImplC obj = new ImplC();
            HelloC stub = (HelloC) UnicastRemoteObject.exportObject((HelloC)obj, 0);

            Registry registry = LocateRegistry.createRegistry(ThreadLocalRandom.current().nextInt(2000, 30000 + 1)); 
            registry.rebind("HelloC",stub);
            
            Object[][] ref_stock_prefacture = getTableData(Liste_PreFacture);
            int nb_ligne_prefacture = 0;
            while(ref_stock_prefacture[nb_ligne_prefacture][0] != null){
                nb_ligne_prefacture++;        
            }
            
            Object[][] table_articles = getTableData(liste_articles);
            int nb_ligne_table_articles = 0;
            while(table_articles[nb_ligne_table_articles][0] != null){
                nb_ligne_table_articles++; 
            }
            
            int last_facture_numero = stub.getLastFacture("SELECT MAX(numero) FROM heptathlon.Factures;");
            last_facture_numero++;           
            
            for (int i = 0; i<nb_ligne_prefacture;i++){  
                for (int j = 0; j<nb_ligne_table_articles;j++){
                    if ( ref_stock_prefacture[i][0].equals(table_articles[j][0])){
                        int oldStock = Integer.parseInt(table_articles[j][4].toString());
                        int factStock = Integer.parseInt(ref_stock_prefacture[i][3].toString());
                        if (oldStock < factStock){
                            Label_erreur_stock.setText("Stock insufisant");
                            boutonCreerFacture.setVisible(false); 
                        }else {
                            int newStock = oldStock - factStock;
                            table_articles[j][4] = newStock;
                            String ref = table_articles[j][0].toString();
                            
                            stub.updateArticles(newStock, table_articles[j][0].toString());

                            String req2 = "INSERT INTO Factures (numero, ref_article, famille, nom, quantite, prix_unitaire, montant) VALUES "
                                    + "("+last_facture_numero+","+ref+",'"+ref_stock_prefacture[i][1]+"','"+ref_stock_prefacture[i][2]
                                    +"',"+ref_stock_prefacture[i][3]+","+ref_stock_prefacture[i][4]+","+ref_stock_prefacture[i][5]+");";
                            stub.addFacture(req2);
                        }  
                    }      
                }         
            } 
            Label_numero_facture.setText("Numéro facture : " + (last_facture_numero)); 
            String req3 = "SELECT numero FROM factures WHERE montant="+montantTotal+";";
            int numero = stub.getNumeroFacture(req3);            
        } catch (Exception e) {           
            e.printStackTrace();
        } 
            
        try{
                     
        // AFFICHAGE ARTICLES - MENU ACCUEIL
        System.out.println("1");
            ImplC obj = new ImplC();
            HelloC stub = (HelloC) UnicastRemoteObject.exportObject((HelloC)obj, 0);
            Registry registry = LocateRegistry.createRegistry(ThreadLocalRandom.current().nextInt(2000, 30000 + 1)); 
            registry.rebind("HelloC",stub);
            
            List<Article> listConsult = stub.getArticles();

            int j=0;
            for (Article s:listConsult) {   
                liste_articles.setValueAt(s.getReference(), j, 0);
                liste_articles.setValueAt(s.getFamille(), j, 1);
                liste_articles.setValueAt(s.getNom(), j, 2);
                liste_articles.setValueAt(s.getPrix_unitaire(), j, 3);
                liste_articles.setValueAt(s.getNb_stock(), j, 4);
                j++;                  
            }
        }catch (Exception e){
            e.printStackTrace(); 
        }    
    }//GEN-LAST:event_boutonCreerFactureMouseClicked
  
    // BOUTON AJOUTER LIGNE A LA PREFACTURE (PANIER)
    private void btn_Fact_add_lineMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Fact_add_lineMouseClicked
        AjoutArtFactDialog.setVisible(true);         
    }//GEN-LAST:event_btn_Fact_add_lineMouseClicked
      
    // BOUTON VALIDATION AJOUT ARTICLE DANS PREFACTURE
    private void btn_ajout_ligne_factMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ajout_ligne_factMouseClicked
        List<Article> liste_pre_facture = new ArrayList<>();
        double montant_ligne = 0;

        try { 
            ImplC obj = new ImplC();
            HelloC stub = (HelloC) UnicastRemoteObject.exportObject((HelloC)obj, 0);
            Registry registry = LocateRegistry.createRegistry(ThreadLocalRandom.current().nextInt(2000, 30000 + 1)); 
            registry.rebind("HelloC",stub);

            int ref_saisie = Integer.parseInt(TF_ref_art_fact.getText());
            int qte_saisie = Integer.parseInt(TF_qte_art_fact.getText());
            String requete = "SELECT * FROM Articles WHERE reference="+ref_saisie+";";

            Article article = stub.getArticlePourFacture(requete);
            if (qte_saisie <= article.getNb_stock()){
                if (article.getReference() != 0){
                    Liste_PreFacture.setValueAt(article.getReference(), i, 0);
                    Liste_PreFacture.setValueAt(article.getFamille(), i, 1);
                    Liste_PreFacture.setValueAt(article.getNom(), i, 2);
                    Liste_PreFacture.setValueAt(qte_saisie, i, 3);
                    Liste_PreFacture.setValueAt(article.getPrix_unitaire(), i, 4);
                    montant_ligne = qte_saisie * article.getPrix_unitaire();
                    Liste_PreFacture.setValueAt(qte_saisie*article.getPrix_unitaire(), i, 5);
                    montantTotal = montantTotal + montant_ligne;
                    TF_Montant_total.setText(String.format("%.2f", montantTotal));  
                    Label_stock_insuffisant.setText("Ajouté");
                } else {
                    i--;
                } 
            } else {
                Label_stock_insuffisant.setText("Stock insuffisant");
                i--;
            }

            for (Article s:liste_pre_facture) {
                Liste_PreFacture.setValueAt(s.getReference(), i, 0);
                Liste_PreFacture.setValueAt(s.getFamille(), i, 1);
                Liste_PreFacture.setValueAt(s.getNom(), i, 2);
                Liste_PreFacture.setValueAt(qte_saisie, i, 3);
                Liste_PreFacture.setValueAt(s.getPrix_unitaire(),i, 4);
                Liste_PreFacture.setValueAt(montant_ligne,i, 5);               
            }  
            i++;  
        } catch (Exception e) {           
            e.printStackTrace();
        }    
    }//GEN-LAST:event_btn_ajout_ligne_factMouseClicked
   
    // BOUTON RECHERCHER DEPUIS RECHERCHE FACTURE DIALOG
    private void boutonValiderRechercheFactureMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boutonValiderRechercheFactureMouseClicked
        Resultat_recherche_facture.setVisible(true);
        int numero_facture_recherchee = Integer.parseInt(TF_Consult_Facture.getText());
        Label_Fact_numero.setText("Facture numéro " + numero_facture_recherchee);
        // CLIC VISUALISER STOCK depuis AccueilCaisse
        try { 
            ImplC obj = new ImplC();
            System.out.println("2");
            HelloC stub = (HelloC) UnicastRemoteObject.exportObject((HelloC)obj, 0);
            Registry registry = LocateRegistry.createRegistry(ThreadLocalRandom.current().nextInt(2000, 30000 + 1)); 
            registry.rebind("HelloC",stub);
            
            
                        System.out.println("2");
            List<Facture> list = stub.getFacture(numero_facture_recherchee); 

            int i=0;
            for (Facture s:list) {
                Liste_resultat_recherche_fact.setValueAt(s.getRef_article(),i, 0);
                Liste_resultat_recherche_fact.setValueAt(s.getFamille(), i, 1);
                Liste_resultat_recherche_fact.setValueAt(s.getNom(), i, 2);
                Liste_resultat_recherche_fact.setValueAt(s.getQuantite(),i, 3);
                Liste_resultat_recherche_fact.setValueAt(s.getPrix_unitaire(), i, 4);
                Liste_resultat_recherche_fact.setValueAt(s.getQuantite()*s.getPrix_unitaire(), i, 5);
                montantFacture = montantFacture + s.getQuantite()*s.getPrix_unitaire();
                TF_Montant_total_Consult_Fact.setText(String.valueOf(montantFacture));
                i++;                  
            }  
        } catch (Exception e) { 
           e.printStackTrace();
        }   
    }//GEN-LAST:event_boutonValiderRechercheFactureMouseClicked
    
    // BOUTON CONSULTATION FACTURE DEPUIS ACCUEIL
    private void btn_consultFactMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_consultFactMouseClicked
        ConsultationFactureDialog.setVisible(true);
    }//GEN-LAST:event_btn_consultFactMouseClicked

    // BOUTON PAIEMENT FACTURE DEPUIS CONSULTATION FACTURE
    private void btn_paiement_factMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_paiement_factMouseClicked
        try { 
            ImplC obj = new ImplC();
            HelloC stub = (HelloC) UnicastRemoteObject.exportObject((HelloC)obj, 0);          
            Registry registry = LocateRegistry.createRegistry(ThreadLocalRandom.current().nextInt(2000, 30000 + 1)); 
            registry.rebind("HelloC",stub);
            
            int num_facture = Integer.parseInt(TF_Consult_Facture.getText());
            double montant = montantFacture;    
            java.sql.Date date = new java.sql.Date(Calendar.getInstance().getTime().getTime());

            boolean cb = Radio_btn_CB.isSelected();
            boolean esp= Radio_btn_especes.isSelected();
            boolean other = Radio_btn_autres.isSelected();
            
            if(cb || esp || other){
                if(cb && !esp && !other){
                    String req ="INSERT INTO Paiements (num_facture, montant, date, mode) VALUES ("+num_facture+","+montant+",'"+date+"','CB');";
                    stub.addPaiement(req);
               }
                if(esp && !cb && !other){
                    String req ="INSERT INTO Paiements (num_facture, montant, date, mode) VALUES ("+num_facture+","+montant+",'"+date+"','especes');";
                    stub.addPaiement(req);         
                } 
                if(other && !cb && !esp){
                    String req ="INSERT INTO Paiements (num_facture, montant, date, mode) VALUES ("+num_facture+","+montant+",'"+date+"','autres');";
                    stub.addPaiement(req);
                }  
            } else {
                Label_Fact_numero.setText("Veuillez sélectionner un mode de paiement");
            }      
        } catch (Exception e) {           
            e.printStackTrace();
        }   
    }//GEN-LAST:event_btn_paiement_factMouseClicked

    private void Radio_btn_especesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Radio_btn_especesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Radio_btn_especesMouseClicked

    //BOUTON OUVRIR FENETRE CALCUL CA
    private void btn_CAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CAMouseClicked
        Calcul_CA_Dialog.setVisible(true);
    }//GEN-LAST:event_btn_CAMouseClicked
 
    // BOUTON CALCULER CA DEPUIS ACCUEIL
    private void btn_calculerCAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_calculerCAMouseClicked
        double CA = 0;     
        try { 
            ImplC obj = new ImplC();
            HelloC stub = (HelloC) UnicastRemoteObject.exportObject((HelloC)obj, 0);
            Registry registry = LocateRegistry.createRegistry(ThreadLocalRandom.current().nextInt(2000, 30000 + 1)); 
            registry.rebind("HelloC",stub);

            Date dateD = dateDebut.getDate();        
            DateFormat oDateFormat = new SimpleDateFormat("yyyy-MM-dd");
            String szDate = oDateFormat.format(dateD);
            
            Date dateF = dateFin.getDate();        
            DateFormat obDateFormat = new SimpleDateFormat("yyyy-MM-dd");
            String szbDate = obDateFormat.format(dateF);

            String req = "SELECT SUM(montant) FROM heptathlon.Paiements WHERE date BETWEEN '"+szDate+"' AND '"+szbDate+"';";
            stub.getCA(req); 
            CA = stub.getCA(req);
        } catch (Exception e) {           
            e.printStackTrace();
        } 
        Label_CA_Total.setText("CA = "+String.valueOf(CA));     
    }//GEN-LAST:event_btn_calculerCAMouseClicked

    private void dateDebutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateDebutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateDebutActionPerformed

    private void dateFinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateFinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateFinActionPerformed

    private void btn_quitMouseClicked(java.awt.event.ActionEvent evt) {
        
    }
    
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccueilCaisse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccueilCaisse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccueilCaisse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccueilCaisse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AccueilCaisse().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog AjoutArtFactDialog;
    private javax.swing.JDialog Calcul_CA_Dialog;
    private javax.swing.JDialog ConsultationFactureDialog;
    private javax.swing.JDialog ConsultationFamille;
    private javax.swing.JDialog ConsultationRef;
    private javax.swing.JDialog CreationFacture;
    private javax.swing.JLabel Label_CA_Total;
    private javax.swing.JLabel Label_Consult_Facture;
    private javax.swing.JLabel Label_Consult_Famille;
    private javax.swing.JLabel Label_Consult_Ref;
    private javax.swing.JLabel Label_Fact_numero;
    private javax.swing.JLabel Label_ValiderAjout1;
    private javax.swing.JLabel Label_ajout_art_qte_fact;
    private javax.swing.JLabel Label_ajout_art_ref_fact;
    private javax.swing.JLabel Label_date_CA_debut;
    private javax.swing.JLabel Label_date_CA_fin;
    private javax.swing.JLabel Label_erreur_stock;
    private javax.swing.JLabel Label_numero_facture;
    private javax.swing.JLabel Label_stock_insuffisant;
    private javax.swing.JTable Liste_PreFacture;
    private javax.swing.JTable Liste_resultat_recherche_fact;
    private javax.swing.JTable Liste_resultat_recherche_fact1;
    private javax.swing.JRadioButton Radio_btn_CB;
    private javax.swing.JRadioButton Radio_btn_autres;
    private javax.swing.JRadioButton Radio_btn_especes;
    private javax.swing.JDialog Resultat_recherche_facture;
    private javax.swing.JLabel Squelette1;
    private javax.swing.JLabel Squelette2;
    private javax.swing.JTextField TF_Consult_Facture;
    private javax.swing.JTextField TF_Consult_Famille;
    private javax.swing.JTextField TF_Consult_Ref;
    private javax.swing.JTextField TF_Montant_total;
    private javax.swing.JTextField TF_Montant_total_Consult_Fact;
    private javax.swing.JTextField TF_Montant_total_Consult_Fact1;
    private javax.swing.JTextField TF_qte_art_fact;
    private javax.swing.JTextField TF_ref_art_fact;
    private javax.swing.JScrollPane Tableau_articles;
    private javax.swing.JDialog TicketCaisse_Dialog;
    private javax.swing.JButton boutonCreerFacture;
    private javax.swing.JButton boutonValiderConsult;
    private javax.swing.JButton boutonValiderFamille;
    private javax.swing.JButton boutonValiderRechercheFacture;
    private javax.swing.JButton btn_CA;
    private javax.swing.JButton btn_Fact_add_line;
    private javax.swing.JButton btn_ajout_ligne_fact;
    private javax.swing.JButton btn_calculerCA;
    private javax.swing.JButton btn_consultFact;
    private javax.swing.JButton btn_consultFamille;
    private javax.swing.JButton btn_consultRef;
    private javax.swing.JButton btn_creaFact;
    private javax.swing.JButton btn_paiement_fact;
    private javax.swing.JButton btn_quit;
    private javax.swing.JButton btn_visualiser_art;
    private org.jdesktop.swingx.JXDatePicker dateDebut;
    private org.jdesktop.swingx.JXDatePicker dateFin;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable liste_articles;
    private javax.swing.JScrollPane liste_facture;
    private javax.swing.JScrollPane liste_facture1;
    // End of variables declaration//GEN-END:variables
}
