package com.heptathlon.heptathlonrmi;

import com.heptathlon.heptathlonrmi.Objets.Facture;
import com.heptathlon.heptathlonrmi.Objets.Article;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.rmi.server.UnicastRemoteObject;
import java.text.DateFormat;
import java.text.SimpleDateFormat;

import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.concurrent.ThreadLocalRandom;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;


public class AccueilCaisse extends javax.swing.JFrame {

    int i = 0;
    int nb_ligne_visualiser = 57;   
    double montantTotal = 0;
    double montantFacture = 0;
    ImplC obj = new ImplC();
    HelloC stub = null;
    boolean allume = false;
 
    public AccueilCaisse() {
        initComponents();
    }
    
    public Object[][] getTableData (JTable table) {
        
        DefaultTableModel dtm = (DefaultTableModel) table.getModel();
        int nRow = dtm.getRowCount(), nCol = dtm.getColumnCount();
        Object[][] tableData = new Object[nRow][nCol];
        for (int i = 0 ; i < nRow ; i++)
            for (int j = 0 ; j < nCol ; j++)
                tableData[i][j] = dtm.getValueAt(i,j);
        
        return tableData;
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ConsultationRef = new javax.swing.JDialog();
        Label_Consult_Ref = new javax.swing.JLabel();
        TF_Consult_Ref = new javax.swing.JTextField();
        boutonValiderConsult = new javax.swing.JButton();
        ConsultationFamille = new javax.swing.JDialog();
        Label_Consult_Famille = new javax.swing.JLabel();
        TF_Consult_Famille = new javax.swing.JTextField();
        boutonValiderFamille = new javax.swing.JButton();
        CreationFacture = new javax.swing.JDialog();
        boutonCreerFacture = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Liste_PreFacture = new javax.swing.JTable();
        TF_Montant_total = new javax.swing.JTextField();
        btn_Fact_add_line = new javax.swing.JButton();
        Label_numero_facture = new javax.swing.JLabel();
        Label_erreur_stock = new javax.swing.JLabel();
        Label_numero_facture1 = new javax.swing.JLabel();
        TF_client_nom = new javax.swing.JTextField();
        AjoutArtFactDialog = new javax.swing.JDialog();
        Label_ajout_art_ref_fact = new javax.swing.JLabel();
        TF_ref_art_fact = new javax.swing.JTextField();
        btn_ajout_ligne_fact = new javax.swing.JButton();
        TF_qte_art_fact = new javax.swing.JTextField();
        Label_ajout_art_qte_fact = new javax.swing.JLabel();
        Label_stock_insuffisant = new javax.swing.JLabel();
        ConsultationFactureDialog = new javax.swing.JDialog();
        Label_Consult_Facture = new javax.swing.JLabel();
        TF_Consult_Facture = new javax.swing.JTextField();
        boutonValiderRechercheFacture = new javax.swing.JButton();
        Resultat_recherche_facture = new javax.swing.JDialog();
        liste_facture = new javax.swing.JScrollPane();
        Liste_resultat_recherche_fact = new javax.swing.JTable();
        TF_Montant_total_Consult_Fact = new javax.swing.JTextField();
        btn_paiement_fact = new javax.swing.JButton();
        Label_Fact_numero = new javax.swing.JLabel();
        ComboPay = new javax.swing.JComboBox<>();
        TF_chercher_facture = new javax.swing.JTextField();
        btn_chercher_facture = new javax.swing.JButton();
        Calcul_CA_Dialog = new javax.swing.JDialog();
        Label_date_CA_debut = new javax.swing.JLabel();
        btn_calculerCA = new javax.swing.JButton();
        Label_date_CA_fin = new javax.swing.JLabel();
        Label_CA_Total = new javax.swing.JLabel();
        dateDebut = new org.jdesktop.swingx.JXDatePicker();
        dateFin = new org.jdesktop.swingx.JXDatePicker();
        btn_visualiser_art = new javax.swing.JButton();
        btn_quit = new javax.swing.JButton();
        Tableau_articles = new javax.swing.JScrollPane();
        liste_articles = new javax.swing.JTable();
        btn_consultRef = new javax.swing.JButton();
        btn_consultFamille = new javax.swing.JButton();
        btn_consultFact = new javax.swing.JButton();
        btn_creaFact = new javax.swing.JButton();
        btn_CA = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        Tableau_factures = new javax.swing.JScrollPane();
        liste_factures = new javax.swing.JTable();
        btn_voir_facture = new javax.swing.JButton();

        ConsultationRef.setTitle("Consultation par référence");
        ConsultationRef.setAlwaysOnTop(true);
        ConsultationRef.setLocation(new java.awt.Point(150, 150));
        ConsultationRef.setResizable(false);
        ConsultationRef.setSize(new java.awt.Dimension(450, 450));

        Label_Consult_Ref.setText("Recherche par référence");
        Label_Consult_Ref.setMaximumSize(new java.awt.Dimension(450, 450));

        TF_Consult_Ref.setToolTipText("");
        TF_Consult_Ref.setMaximumSize(new java.awt.Dimension(450, 450));

        boutonValiderConsult.setText("Valider");
        boutonValiderConsult.setToolTipText("");
        boutonValiderConsult.setMaximumSize(new java.awt.Dimension(450, 450));
        boutonValiderConsult.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boutonValiderConsultMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ConsultationRefLayout = new javax.swing.GroupLayout(ConsultationRef.getContentPane());
        ConsultationRef.getContentPane().setLayout(ConsultationRefLayout);
        ConsultationRefLayout.setHorizontalGroup(
            ConsultationRefLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConsultationRefLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(Label_Consult_Ref, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(ConsultationRefLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(boutonValiderConsult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TF_Consult_Ref, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        ConsultationRefLayout.setVerticalGroup(
            ConsultationRefLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConsultationRefLayout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(ConsultationRefLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TF_Consult_Ref, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_Consult_Ref, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(boutonValiderConsult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        ConsultationFamille.setTitle("Consultation par famille");
        ConsultationFamille.setAlwaysOnTop(true);
        ConsultationFamille.setLocation(new java.awt.Point(150, 150));
        ConsultationFamille.setResizable(false);
        ConsultationFamille.setSize(new java.awt.Dimension(450, 450));

        Label_Consult_Famille.setText("Recherche par famille");
        Label_Consult_Famille.setMaximumSize(new java.awt.Dimension(450, 450));

        TF_Consult_Famille.setToolTipText("");
        TF_Consult_Famille.setMaximumSize(new java.awt.Dimension(450, 450));

        boutonValiderFamille.setText("Valider");
        boutonValiderFamille.setToolTipText("");
        boutonValiderFamille.setMaximumSize(new java.awt.Dimension(450, 450));
        boutonValiderFamille.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boutonValiderFamilleMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ConsultationFamilleLayout = new javax.swing.GroupLayout(ConsultationFamille.getContentPane());
        ConsultationFamille.getContentPane().setLayout(ConsultationFamilleLayout);
        ConsultationFamilleLayout.setHorizontalGroup(
            ConsultationFamilleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConsultationFamilleLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(Label_Consult_Famille, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(ConsultationFamilleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(boutonValiderFamille, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TF_Consult_Famille, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        ConsultationFamilleLayout.setVerticalGroup(
            ConsultationFamilleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConsultationFamilleLayout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(ConsultationFamilleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TF_Consult_Famille, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_Consult_Famille, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(boutonValiderFamille, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        CreationFacture.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        CreationFacture.setTitle("Pre - facture");
        CreationFacture.setAlwaysOnTop(true);
        CreationFacture.setLocation(new java.awt.Point(150, 150));
        CreationFacture.setResizable(false);
        CreationFacture.setSize(new java.awt.Dimension(450, 450));

        boutonCreerFacture.setText("Créer facture");
        boutonCreerFacture.setToolTipText("");
        boutonCreerFacture.setMaximumSize(new java.awt.Dimension(450, 450));
        boutonCreerFacture.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boutonCreerFactureMouseClicked(evt);
            }
        });

        Liste_PreFacture.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Référence article", "Famille", "Nom", "Quantité", "PU", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Liste_PreFacture.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(Liste_PreFacture);
        if (Liste_PreFacture.getColumnModel().getColumnCount() > 0) {
            Liste_PreFacture.getColumnModel().getColumn(0).setResizable(false);
            Liste_PreFacture.getColumnModel().getColumn(1).setResizable(false);
            Liste_PreFacture.getColumnModel().getColumn(2).setResizable(false);
            Liste_PreFacture.getColumnModel().getColumn(3).setResizable(false);
            Liste_PreFacture.getColumnModel().getColumn(4).setResizable(false);
            Liste_PreFacture.getColumnModel().getColumn(5).setResizable(false);
        }

        TF_Montant_total.setText("Montant total");

        btn_Fact_add_line.setText("Ajouter article");
        btn_Fact_add_line.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_Fact_add_lineMouseClicked(evt);
            }
        });

        Label_numero_facture.setText("Numéro facture");
        Label_numero_facture.setToolTipText("");

        Label_numero_facture1.setText("Client :");
        Label_numero_facture1.setToolTipText("");

        TF_client_nom.setText("Nom du Client");

        javax.swing.GroupLayout CreationFactureLayout = new javax.swing.GroupLayout(CreationFacture.getContentPane());
        CreationFacture.getContentPane().setLayout(CreationFactureLayout);
        CreationFactureLayout.setHorizontalGroup(
            CreationFactureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreationFactureLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CreationFactureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CreationFactureLayout.createSequentialGroup()
                        .addGroup(CreationFactureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CreationFactureLayout.createSequentialGroup()
                                .addComponent(btn_Fact_add_line, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CreationFactureLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(Label_numero_facture, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(99, 99, 99)
                                .addComponent(TF_Montant_total, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 831, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CreationFactureLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(CreationFactureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CreationFactureLayout.createSequentialGroup()
                                .addComponent(Label_erreur_stock)
                                .addGap(228, 228, 228))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CreationFactureLayout.createSequentialGroup()
                                .addComponent(Label_numero_facture1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(TF_client_nom, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
            .addGroup(CreationFactureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CreationFactureLayout.createSequentialGroup()
                    .addContainerGap(679, Short.MAX_VALUE)
                    .addComponent(boutonCreerFacture, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(19, 19, 19)))
        );
        CreationFactureLayout.setVerticalGroup(
            CreationFactureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreationFactureLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_Fact_add_line, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(CreationFactureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_numero_facture1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TF_client_nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(CreationFactureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Label_numero_facture, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TF_Montant_total))
                .addGap(53, 53, 53)
                .addComponent(Label_erreur_stock)
                .addGap(32, 32, 32))
            .addGroup(CreationFactureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CreationFactureLayout.createSequentialGroup()
                    .addContainerGap(419, Short.MAX_VALUE)
                    .addComponent(boutonCreerFacture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(30, 30, 30)))
        );

        AjoutArtFactDialog.setTitle("Ajout article pour pre - facture");
        AjoutArtFactDialog.setAlwaysOnTop(true);
        AjoutArtFactDialog.setLocation(new java.awt.Point(150, 150));
        AjoutArtFactDialog.setResizable(false);
        AjoutArtFactDialog.setSize(new java.awt.Dimension(450, 450));

        Label_ajout_art_ref_fact.setText("Référence");
        Label_ajout_art_ref_fact.setMaximumSize(new java.awt.Dimension(450, 450));

        TF_ref_art_fact.setToolTipText("");
        TF_ref_art_fact.setMaximumSize(new java.awt.Dimension(450, 450));

        btn_ajout_ligne_fact.setText("Ajouter");
        btn_ajout_ligne_fact.setToolTipText("");
        btn_ajout_ligne_fact.setMaximumSize(new java.awt.Dimension(450, 450));
        btn_ajout_ligne_fact.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ajout_ligne_factMouseClicked(evt);
            }
        });

        TF_qte_art_fact.setToolTipText("");
        TF_qte_art_fact.setMaximumSize(new java.awt.Dimension(450, 450));

        Label_ajout_art_qte_fact.setText("Quantité");
        Label_ajout_art_qte_fact.setMaximumSize(new java.awt.Dimension(450, 450));

        javax.swing.GroupLayout AjoutArtFactDialogLayout = new javax.swing.GroupLayout(AjoutArtFactDialog.getContentPane());
        AjoutArtFactDialog.getContentPane().setLayout(AjoutArtFactDialogLayout);
        AjoutArtFactDialogLayout.setHorizontalGroup(
            AjoutArtFactDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AjoutArtFactDialogLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(AjoutArtFactDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label_ajout_art_ref_fact, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                    .addComponent(Label_ajout_art_qte_fact, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AjoutArtFactDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TF_qte_art_fact, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                    .addComponent(TF_ref_art_fact, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE))
                .addGap(105, 105, 105))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AjoutArtFactDialogLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_ajout_ligne_fact, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91))
            .addGroup(AjoutArtFactDialogLayout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(Label_stock_insuffisant, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AjoutArtFactDialogLayout.setVerticalGroup(
            AjoutArtFactDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AjoutArtFactDialogLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(AjoutArtFactDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TF_ref_art_fact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_ajout_art_ref_fact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AjoutArtFactDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_ajout_art_qte_fact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TF_qte_art_fact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label_stock_insuffisant, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_ajout_ligne_fact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        ConsultationFactureDialog.setTitle("Consultation facture");
        ConsultationFactureDialog.setAlwaysOnTop(true);
        ConsultationFactureDialog.setLocation(new java.awt.Point(150, 150));
        ConsultationFactureDialog.setResizable(false);
        ConsultationFactureDialog.setSize(new java.awt.Dimension(450, 450));

        Label_Consult_Facture.setText("Recherche par facture");
        Label_Consult_Facture.setMaximumSize(new java.awt.Dimension(450, 450));

        TF_Consult_Facture.setToolTipText("");
        TF_Consult_Facture.setMaximumSize(new java.awt.Dimension(450, 450));

        boutonValiderRechercheFacture.setText("Valider");
        boutonValiderRechercheFacture.setToolTipText("");
        boutonValiderRechercheFacture.setMaximumSize(new java.awt.Dimension(450, 450));
        boutonValiderRechercheFacture.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boutonValiderRechercheFactureMouseClicked(evt);
            }
        });
        boutonValiderRechercheFacture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonValiderRechercheFactureActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ConsultationFactureDialogLayout = new javax.swing.GroupLayout(ConsultationFactureDialog.getContentPane());
        ConsultationFactureDialog.getContentPane().setLayout(ConsultationFactureDialogLayout);
        ConsultationFactureDialogLayout.setHorizontalGroup(
            ConsultationFactureDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConsultationFactureDialogLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(Label_Consult_Facture, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(ConsultationFactureDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(boutonValiderRechercheFacture, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TF_Consult_Facture, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        ConsultationFactureDialogLayout.setVerticalGroup(
            ConsultationFactureDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConsultationFactureDialogLayout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(ConsultationFactureDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TF_Consult_Facture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_Consult_Facture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(boutonValiderRechercheFacture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        Resultat_recherche_facture.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        Resultat_recherche_facture.setTitle("Facture");
        Resultat_recherche_facture.setAlwaysOnTop(true);
        Resultat_recherche_facture.setLocation(new java.awt.Point(150, 150));
        Resultat_recherche_facture.setResizable(false);
        Resultat_recherche_facture.setSize(new java.awt.Dimension(950, 450));

        Liste_resultat_recherche_fact.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Référence article", "Famille", "Nom", "Quantité", "PU", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Liste_resultat_recherche_fact.getTableHeader().setReorderingAllowed(false);
        liste_facture.setViewportView(Liste_resultat_recherche_fact);
        if (Liste_resultat_recherche_fact.getColumnModel().getColumnCount() > 0) {
            Liste_resultat_recherche_fact.getColumnModel().getColumn(0).setResizable(false);
            Liste_resultat_recherche_fact.getColumnModel().getColumn(1).setResizable(false);
            Liste_resultat_recherche_fact.getColumnModel().getColumn(2).setResizable(false);
            Liste_resultat_recherche_fact.getColumnModel().getColumn(3).setResizable(false);
            Liste_resultat_recherche_fact.getColumnModel().getColumn(4).setResizable(false);
            Liste_resultat_recherche_fact.getColumnModel().getColumn(5).setResizable(false);
        }

        TF_Montant_total_Consult_Fact.setText("Montant total");

        btn_paiement_fact.setText("Payer");
        btn_paiement_fact.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_paiement_factMouseClicked(evt);
            }
        });

        Label_Fact_numero.setFont(new java.awt.Font("Cantarell", 0, 36)); // NOI18N
        Label_Fact_numero.setText("Facture : ");

        ComboPay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "especes", "CB", "Autres" }));

        btn_chercher_facture.setText("Chercher");
        btn_chercher_facture.setLocation(new java.awt.Point(-32400, -32714));
        btn_chercher_facture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_chercher_factureActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Resultat_recherche_factureLayout = new javax.swing.GroupLayout(Resultat_recherche_facture.getContentPane());
        Resultat_recherche_facture.getContentPane().setLayout(Resultat_recherche_factureLayout);
        Resultat_recherche_factureLayout.setHorizontalGroup(
            Resultat_recherche_factureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Resultat_recherche_factureLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Resultat_recherche_factureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Resultat_recherche_factureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(liste_facture, javax.swing.GroupLayout.PREFERRED_SIZE, 747, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(Resultat_recherche_factureLayout.createSequentialGroup()
                            .addComponent(TF_Montant_total_Consult_Fact, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(ComboPay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(btn_paiement_fact, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Resultat_recherche_factureLayout.createSequentialGroup()
                        .addComponent(Label_Fact_numero)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TF_chercher_facture, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_chercher_facture)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        Resultat_recherche_factureLayout.setVerticalGroup(
            Resultat_recherche_factureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Resultat_recherche_factureLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(Resultat_recherche_factureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TF_chercher_facture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_chercher_facture)
                    .addComponent(Label_Fact_numero, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(liste_facture, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Resultat_recherche_factureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TF_Montant_total_Consult_Fact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboPay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_paiement_fact)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        Calcul_CA_Dialog.setTitle("Calcul CA");
        Calcul_CA_Dialog.setAlwaysOnTop(true);
        Calcul_CA_Dialog.setLocation(new java.awt.Point(150, 150));
        Calcul_CA_Dialog.setSize(new java.awt.Dimension(878, 160));

        Label_date_CA_debut.setText("Date de début");
        Label_date_CA_debut.setMaximumSize(new java.awt.Dimension(450, 450));

        btn_calculerCA.setText("Calculer");
        btn_calculerCA.setToolTipText("");
        btn_calculerCA.setMaximumSize(new java.awt.Dimension(450, 450));
        btn_calculerCA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_calculerCAMouseClicked(evt);
            }
        });

        Label_date_CA_fin.setText("Date de fin");
        Label_date_CA_fin.setMaximumSize(new java.awt.Dimension(450, 450));

        Label_CA_Total.setText("Total CA");

        dateDebut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateDebutActionPerformed(evt);
            }
        });

        dateFin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateFinActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Calcul_CA_DialogLayout = new javax.swing.GroupLayout(Calcul_CA_Dialog.getContentPane());
        Calcul_CA_Dialog.getContentPane().setLayout(Calcul_CA_DialogLayout);
        Calcul_CA_DialogLayout.setHorizontalGroup(
            Calcul_CA_DialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Calcul_CA_DialogLayout.createSequentialGroup()
                .addGroup(Calcul_CA_DialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Calcul_CA_DialogLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(Label_date_CA_debut, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(141, 141, 141)
                        .addComponent(Label_date_CA_fin, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Calcul_CA_DialogLayout.createSequentialGroup()
                        .addGroup(Calcul_CA_DialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Calcul_CA_DialogLayout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(dateDebut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Calcul_CA_DialogLayout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addComponent(Label_CA_Total, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(69, 69, 69)
                        .addGroup(Calcul_CA_DialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dateFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Calcul_CA_DialogLayout.createSequentialGroup()
                                .addComponent(btn_calculerCA, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)))))
                .addContainerGap(263, Short.MAX_VALUE))
        );
        Calcul_CA_DialogLayout.setVerticalGroup(
            Calcul_CA_DialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Calcul_CA_DialogLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(Calcul_CA_DialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_date_CA_debut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_date_CA_fin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Calcul_CA_DialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateDebut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(Calcul_CA_DialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_calculerCA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_CA_Total))
                .addContainerGap(213, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        btn_visualiser_art.setText("Voir Articles");
        btn_visualiser_art.setToolTipText("");
        btn_visualiser_art.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_visualiser_artMouseClicked(evt);
            }
        });

        btn_quit.setText("Quitter");

        liste_articles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Reference", "Famille", "Nom", "Prix unitaire", "Nb stock"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        liste_articles.setColumnSelectionAllowed(true);
        liste_articles.setRowSelectionAllowed(false);
        liste_articles.getTableHeader().setReorderingAllowed(false);
        Tableau_articles.setViewportView(liste_articles);
        liste_articles.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        if (liste_articles.getColumnModel().getColumnCount() > 0) {
            liste_articles.getColumnModel().getColumn(0).setResizable(false);
            liste_articles.getColumnModel().getColumn(1).setResizable(false);
            liste_articles.getColumnModel().getColumn(1).setHeaderValue("Famille");
            liste_articles.getColumnModel().getColumn(2).setResizable(false);
            liste_articles.getColumnModel().getColumn(2).setHeaderValue("Nom");
            liste_articles.getColumnModel().getColumn(3).setResizable(false);
            liste_articles.getColumnModel().getColumn(3).setHeaderValue("Prix unitaire");
            liste_articles.getColumnModel().getColumn(4).setResizable(false);
            liste_articles.getColumnModel().getColumn(4).setHeaderValue("Nb stock");
        }

        btn_consultRef.setText("Chercher Référence");
        btn_consultRef.setPreferredSize(new java.awt.Dimension(119, 29));
        btn_consultRef.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_consultRefMouseClicked(evt);
            }
        });

        btn_consultFamille.setText("Chercher Famille");
        btn_consultFamille.setPreferredSize(new java.awt.Dimension(119, 29));
        btn_consultFamille.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_consultFamilleMouseClicked(evt);
            }
        });

        btn_consultFact.setText("Détail Facture");
        btn_consultFact.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_consultFactMouseClicked(evt);
            }
        });
        btn_consultFact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_consultFactActionPerformed(evt);
            }
        });

        btn_creaFact.setText("Nouvelle Facture");
        btn_creaFact.setPreferredSize(new java.awt.Dimension(119, 29));
        btn_creaFact.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_creaFactMouseClicked(evt);
            }
        });

        btn_CA.setText("Chiffre d'Affaire");
        btn_CA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_CAMouseClicked(evt);
            }
        });

        jButton1.setText("facture en fin de journée ( à faire)");

        liste_factures.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Reference", "Montant", "Client"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Double.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        liste_factures.setRowSelectionAllowed(false);
        liste_factures.getTableHeader().setReorderingAllowed(false);
        Tableau_factures.setViewportView(liste_factures);
        liste_factures.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        if (liste_factures.getColumnModel().getColumnCount() > 0) {
            liste_factures.getColumnModel().getColumn(0).setResizable(false);
            liste_factures.getColumnModel().getColumn(2).setResizable(false);
        }

        btn_voir_facture.setText("Voir Factures");
        btn_voir_facture.setToolTipText("");
        btn_voir_facture.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_voir_factureMouseClicked(evt);
            }
        });
        btn_voir_facture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_voir_factureActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btn_consultRef, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_visualiser_art, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_consultFamille, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_voir_facture, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_creaFact, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_consultFact, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_quit))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(btn_CA, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Tableau_factures, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Tableau_articles, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 12, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_visualiser_art)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_consultRef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_consultFamille, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(149, 149, 149)
                        .addComponent(btn_voir_facture)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_creaFact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_consultFact)
                        .addGap(50, 50, 50)
                        .addComponent(btn_CA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Tableau_articles, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Tableau_factures, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_quit)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void start() {
        if (!allume) {
            try {
                stub = (HelloC) UnicastRemoteObject.exportObject((HelloC) obj, 0);
                Registry registry = null;
                registry = LocateRegistry.createRegistry(ThreadLocalRandom.current().nextInt(2000, 30000 + 1));
                registry.rebind("HelloC", stub);
                allume = true;
            } catch (Exception e) {
                e.printStackTrace();
            }
        } 
    }
    
    private void showArticles() {
        try{
            start();
            List<Article> listConsult = stub.getArticles();

            int j=0;
            for (Article s:listConsult) {   
                liste_articles.setValueAt(s.getReference(), j, 0);
                liste_articles.setValueAt(s.getFamille(), j, 1);
                liste_articles.setValueAt(s.getNom(), j, 2);
                liste_articles.setValueAt(s.getPrix_unitaire(), j, 3);
                liste_articles.setValueAt(s.getNb_stock(), j, 4);
                j++;                  
            }
        }catch (Exception e){
            e.printStackTrace(); 
        } 
    }
    // BOUTON VISUALISER DEPUIS ACCUEIL
    private void btn_visualiser_artMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_visualiser_artMouseClicked
        try { 
            start();
            List<Article> list = stub.getArticles(); 
            int i=0;
            for (Article s:list) {
                liste_articles.setValueAt(s.getReference(), i,0);
                liste_articles.setValueAt(s.getFamille(), i,1);
                liste_articles.setValueAt(s.getNom(), i,2);
                liste_articles.setValueAt(s.getPrix_unitaire(), i,3);
                liste_articles.setValueAt(s.getNb_stock(), i,4);
                i++;                  
            }  
        } catch (Exception e) { 
            e.printStackTrace();
        }   
    }//GEN-LAST:event_btn_visualiser_artMouseClicked

    // BOUTON CONSULTATION PAR REFERENCE DEPUIS ACCUEIL
    private void btn_consultRefMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_consultRefMouseClicked
        ConsultationRef.setVisible(true);
        TF_Consult_Ref.setText("");
    }//GEN-LAST:event_btn_consultRefMouseClicked
  
    // BOUTON CONSULTATION PAR FAMILLE DEPUIS ACCUEIL
    private void btn_consultFamilleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_consultFamilleMouseClicked
        ConsultationFamille.setVisible(true);
        TF_Consult_Famille.setText("");      
    }//GEN-LAST:event_btn_consultFamilleMouseClicked
 
    // BOUTON CHERCHER PAR REFERENCE DEPUIS DIALOGCONSULTREFERENCE
    private void boutonValiderConsultMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boutonValiderConsultMouseClicked
        try { 
            start();
            List<Article> listConsult = stub.getArticle("ref", TF_Consult_Ref.getText());

            int i = 0;
            for (Article s:listConsult) {   
                liste_articles.setValueAt(s.getReference(), i, 0);
                liste_articles.setValueAt(s.getFamille(), i, 1);
                liste_articles.setValueAt(s.getNom(), i, 2);
                liste_articles.setValueAt(s.getPrix_unitaire(), i, 3);
                liste_articles.setValueAt(s.getNb_stock(), i, 4);
                i++;                  
            }  
        } catch (Exception e) { 
            e.printStackTrace();
        } 
        int j = 1;
        while (j < nb_ligne_visualiser){
            liste_articles.setValueAt(null,j, 0) ;  
            liste_articles.setValueAt("", j, 1);
            liste_articles.setValueAt("", j, 2);
            liste_articles.setValueAt(null, j, 3);
            liste_articles.setValueAt(null, j, 4);
            j++;
        }
    }//GEN-LAST:event_boutonValiderConsultMouseClicked
   
    // BOUTON CHERCHER PAR FAMILLE DEPUIS DIALOGCONSULTFAMILLE
    private void boutonValiderFamilleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boutonValiderFamilleMouseClicked
        try { 
            start();
            String famille_saisie = TF_Consult_Famille.getText();
            List<Article> list = stub.getArticle("famille", famille_saisie);
            
            int j=0;
            for (Article l:list) {   
                liste_articles.setValueAt(l.getReference(), j, 0);
                liste_articles.setValueAt(l.getFamille(), j, 1);
                liste_articles.setValueAt(l.getNom(), j, 2);
                liste_articles.setValueAt(l.getPrix_unitaire(), j, 3);
                liste_articles.setValueAt(l.getNb_stock(), j, 4);
                j++;                  
            }        
            
            int length = list.size();
            while ( length+1 <= nb_ligne_visualiser ){
                liste_articles.setValueAt(null,length, 0) ;  
                liste_articles.setValueAt("", length, 1);
                liste_articles.setValueAt("", length, 2);
                liste_articles.setValueAt(null, length, 3);
                liste_articles.setValueAt(null, length, 4);
                length++;
            }
        } catch (Exception e) { 
           e.printStackTrace();
        } 
    }//GEN-LAST:event_boutonValiderFamilleMouseClicked
  
    // BOUTON CREATION FACTURE DEPUIS ACCUEIL
    private void btn_creaFactMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_creaFactMouseClicked
        CreationFacture.setVisible(true);    
    }//GEN-LAST:event_btn_creaFactMouseClicked
   
    // BOUTON CREER FACTURE DEPUIS CREER FACTURE DIALOG
    private void boutonCreerFactureMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boutonCreerFactureMouseClicked
        try { 
            start();       
            Object[][] ref_stock_prefacture = getTableData(Liste_PreFacture);
            int nb_ligne_prefacture = 0;
            while(ref_stock_prefacture[nb_ligne_prefacture][0] != null){
                nb_ligne_prefacture++;        
            }
            
            Object[][] table_articles = getTableData(liste_articles);
            int nb_ligne_table_articles = 0;
            while(table_articles[nb_ligne_table_articles][0] != null){
                nb_ligne_table_articles++; 
            }
            String client = TF_client_nom.getText();
            int last_facture_numero = stub.getNumero("facture");
            last_facture_numero++;           
            
            for (int i = 0; i < nb_ligne_prefacture;i++){  
                for (int j = 0; j < nb_ligne_table_articles;j++){
                    if ( ref_stock_prefacture[i][0].equals(table_articles[j][0])){
                        int oldStock = Integer.parseInt(table_articles[j][4].toString());
                        int factStock = Integer.parseInt(ref_stock_prefacture[i][3].toString());
                        if (oldStock < factStock){
                            Label_erreur_stock.setText("Stock insufisant");
                            boutonCreerFacture.setVisible(false); 
                        }else {
                            int newStock = oldStock - factStock;
                            table_articles[j][4] = newStock;
                            stub.addFacture(last_facture_numero+"", table_articles[j][0].toString(), ref_stock_prefacture[i][1].toString(), 
                                    ref_stock_prefacture[i][2].toString(), ref_stock_prefacture[i][3].toString(), 
                                    ref_stock_prefacture[i][4].toString(), ref_stock_prefacture[i][5].toString(), client);    
                            stub.updateArticles(newStock, table_articles[j][0].toString());
                        }  
                    }      
                }         
            } 
            int num = stub.getNumero("facture") + 1;
            Label_numero_facture.setText("Numéro facture : " + stub.getNumero("facture")); 
            showArticles();
        } catch (Exception e) {           
            e.printStackTrace();
        }          
    }//GEN-LAST:event_boutonCreerFactureMouseClicked
  
    // BOUTON AJOUTER LIGNE A LA PREFACTURE (PANIER)
    private void btn_Fact_add_lineMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Fact_add_lineMouseClicked
        AjoutArtFactDialog.setVisible(true);         
    }//GEN-LAST:event_btn_Fact_add_lineMouseClicked
      
    // BOUTON VALIDATION AJOUT ARTICLE DANS PREFACTURE
    private void btn_ajout_ligne_factMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ajout_ligne_factMouseClicked
        start();
        List<Article> liste_pre_facture = new ArrayList<>();
        double montant_ligne = 0;

        try { 
            int ref_saisie = Integer.parseInt(TF_ref_art_fact.getText());
            int qte_saisie = Integer.parseInt(TF_qte_art_fact.getText());
            liste_pre_facture = stub.getArticle("ref", TF_ref_art_fact.getText()); 
            for(Article s:liste_pre_facture) {
                if (qte_saisie <= s.getNb_stock()){
                        Liste_PreFacture.setValueAt(s.getReference(), i, 0);
                        Liste_PreFacture.setValueAt(s.getFamille(), i, 1);
                        Liste_PreFacture.setValueAt(s.getNom(), i, 2);
                        Liste_PreFacture.setValueAt(qte_saisie, i, 3);
                        Liste_PreFacture.setValueAt(s.getPrix_unitaire(), i, 4);
                        montant_ligne = qte_saisie * s.getPrix_unitaire();
                        Liste_PreFacture.setValueAt(qte_saisie*s.getPrix_unitaire(), i, 5);
                        montantTotal = montantTotal + montant_ligne;
                        TF_Montant_total.setText(String.format("%.2f", montantTotal));  
                        Label_stock_insuffisant.setText("Ajouté");
                } else {
                    Label_stock_insuffisant.setText("Stock insuffisant");
                    i--;
                }
            }
            for (Article s:liste_pre_facture) {
                Liste_PreFacture.setValueAt(s.getReference(), i, 0);
                Liste_PreFacture.setValueAt(s.getFamille(), i, 1);
                Liste_PreFacture.setValueAt(s.getNom(), i, 2);
                Liste_PreFacture.setValueAt(qte_saisie, i, 3);
                Liste_PreFacture.setValueAt(s.getPrix_unitaire(),i, 4);
                Liste_PreFacture.setValueAt(montant_ligne,i, 5);               
            }  
            i++;  
        } catch (Exception e) {           
            e.printStackTrace();
        }    
    }//GEN-LAST:event_btn_ajout_ligne_factMouseClicked
   
    // BOUTON RECHERCHER DEPUIS RECHERCHE FACTURE DIALOG
    private void boutonValiderRechercheFactureMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boutonValiderRechercheFactureMouseClicked
        
          
    }//GEN-LAST:event_boutonValiderRechercheFactureMouseClicked
    
    // BOUTON CONSULTATION FACTURE DEPUIS ACCUEIL
    private void btn_consultFactMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_consultFactMouseClicked

    }//GEN-LAST:event_btn_consultFactMouseClicked

    //BOUTON OUVRIR FENETRE CALCUL CA
    private void btn_CAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CAMouseClicked
        Calcul_CA_Dialog.setVisible(true);
    }//GEN-LAST:event_btn_CAMouseClicked
 
    // BOUTON CALCULER CA DEPUIS ACCUEIL
    private void btn_calculerCAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_calculerCAMouseClicked
        start();
        double CA = 0;
        try { 
            Date dateD = dateDebut.getDate();        
            DateFormat oDateFormat = new SimpleDateFormat("yyyy-MM-dd");
            String dDate = oDateFormat.format(dateD);
            
            Date dateF = dateFin.getDate();        
            DateFormat obDateFormat = new SimpleDateFormat("yyyy-MM-dd");
            String fDate = obDateFormat.format(dateF);

            CA = stub.getCA(dDate, fDate);
        } catch (Exception e) {           
            e.printStackTrace();
        } 
        Label_CA_Total.setText("CA = "+String.valueOf(CA));     
    }//GEN-LAST:event_btn_calculerCAMouseClicked

    private void dateDebutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateDebutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateDebutActionPerformed

    private void dateFinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateFinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateFinActionPerformed

    private void btn_voir_factureMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_voir_factureMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_voir_factureMouseClicked

    private void btn_voir_factureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_voir_factureActionPerformed
        try { 
            start();
            List<Facture> list = stub.getFactures(); 
            int i = 0; double montant = 0; int ref = 1; String client = "";
            if (list.size() != 0) {
                for (int j = 0; j <= list.size(); j++) {
                    if (j < list.size()) {
                        if (ref == list.get(j).getRef_facture()) {
                            montant += list.get(j).getMontant();
                            client = list.get(j).getClient();
                        }else {
                            liste_factures.setValueAt(ref, i, 0);
                            liste_factures.setValueAt(montant, i, 1);
                            liste_factures.setValueAt(client, i, 2);
                            i++; 
                            ref = list.get(j).getRef_facture();
                            montant = list.get(j).getMontant();
                        }  
                    }else{
                        liste_factures.setValueAt(ref, i, 0);
                        liste_factures.setValueAt(montant, i, 1);
                        liste_factures.setValueAt(client, i, 2);
                    }
                }
            }
             
        } catch (Exception e) { 
            e.printStackTrace();
        }   
    }//GEN-LAST:event_btn_voir_factureActionPerformed

    private void btn_consultFactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_consultFactActionPerformed
        Resultat_recherche_facture.setVisible(true);
    }//GEN-LAST:event_btn_consultFactActionPerformed

    private void boutonValiderRechercheFactureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonValiderRechercheFactureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boutonValiderRechercheFactureActionPerformed

    private void btn_chercher_factureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_chercher_factureActionPerformed
        int ref = Integer.parseInt(TF_chercher_facture.getText());
        Label_Fact_numero.setText("Facture");
        try {
            List<Facture> list = stub.getFacture(ref);
            int i=0;
            for (Facture s:list) {
                Liste_resultat_recherche_fact.setValueAt(s.getRef_article(),i, 0);
                Liste_resultat_recherche_fact.setValueAt(s.getFamille(), i, 1);
                Liste_resultat_recherche_fact.setValueAt(s.getNom(), i, 2);
                Liste_resultat_recherche_fact.setValueAt(s.getQuantite(),i, 3);
                Liste_resultat_recherche_fact.setValueAt(s.getPrix_unitaire(), i, 4);
                Liste_resultat_recherche_fact.setValueAt(s.getQuantite()*s.getPrix_unitaire(), i, 5);
                montantFacture = montantFacture + s.getQuantite()*s.getPrix_unitaire();
                TF_Montant_total_Consult_Fact.setText(String.valueOf(montantFacture));
                i++;
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn_chercher_factureActionPerformed

    // BOUTON PAIEMENT FACTURE DEPUIS CONSULTATION FACTURE
    private void btn_paiement_factMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_paiement_factMouseClicked
        start();
        try {
            btn_paiement_fact.setText("Payer");
            if (!"".equals(TF_chercher_facture.getText())) {
                int num_facture = Integer.parseInt(TF_chercher_facture.getText());
                double montant = montantFacture;
                java.sql.Date date = new java.sql.Date(Calendar.getInstance().getTime().getTime());
                String moyen = ComboPay.getSelectedItem().toString();
                stub.addPaiement(num_facture+"", montant+"", date+"", moyen);
                Resultat_recherche_facture.setVisible(false);
            }
        } catch (Exception e) {
            btn_paiement_fact.setText("Erreur");
        }
    }//GEN-LAST:event_btn_paiement_factMouseClicked

    private void btn_quitMouseClicked(java.awt.event.ActionEvent evt) {
        
    }
    
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccueilCaisse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccueilCaisse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccueilCaisse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccueilCaisse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AccueilCaisse().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog AjoutArtFactDialog;
    private javax.swing.JDialog Calcul_CA_Dialog;
    private javax.swing.JComboBox<String> ComboPay;
    private javax.swing.JDialog ConsultationFactureDialog;
    private javax.swing.JDialog ConsultationFamille;
    private javax.swing.JDialog ConsultationRef;
    private javax.swing.JDialog CreationFacture;
    private javax.swing.JLabel Label_CA_Total;
    private javax.swing.JLabel Label_Consult_Facture;
    private javax.swing.JLabel Label_Consult_Famille;
    private javax.swing.JLabel Label_Consult_Ref;
    private javax.swing.JLabel Label_Fact_numero;
    private javax.swing.JLabel Label_ajout_art_qte_fact;
    private javax.swing.JLabel Label_ajout_art_ref_fact;
    private javax.swing.JLabel Label_date_CA_debut;
    private javax.swing.JLabel Label_date_CA_fin;
    private javax.swing.JLabel Label_erreur_stock;
    private javax.swing.JLabel Label_numero_facture;
    private javax.swing.JLabel Label_numero_facture1;
    private javax.swing.JLabel Label_stock_insuffisant;
    private javax.swing.JTable Liste_PreFacture;
    private javax.swing.JTable Liste_resultat_recherche_fact;
    private javax.swing.JDialog Resultat_recherche_facture;
    private javax.swing.JTextField TF_Consult_Facture;
    private javax.swing.JTextField TF_Consult_Famille;
    private javax.swing.JTextField TF_Consult_Ref;
    private javax.swing.JTextField TF_Montant_total;
    private javax.swing.JTextField TF_Montant_total_Consult_Fact;
    private javax.swing.JTextField TF_chercher_facture;
    private javax.swing.JTextField TF_client_nom;
    private javax.swing.JTextField TF_qte_art_fact;
    private javax.swing.JTextField TF_ref_art_fact;
    private javax.swing.JScrollPane Tableau_articles;
    private javax.swing.JScrollPane Tableau_factures;
    private javax.swing.JButton boutonCreerFacture;
    private javax.swing.JButton boutonValiderConsult;
    private javax.swing.JButton boutonValiderFamille;
    private javax.swing.JButton boutonValiderRechercheFacture;
    private javax.swing.JButton btn_CA;
    private javax.swing.JButton btn_Fact_add_line;
    private javax.swing.JButton btn_ajout_ligne_fact;
    private javax.swing.JButton btn_calculerCA;
    private javax.swing.JButton btn_chercher_facture;
    private javax.swing.JButton btn_consultFact;
    private javax.swing.JButton btn_consultFamille;
    private javax.swing.JButton btn_consultRef;
    private javax.swing.JButton btn_creaFact;
    private javax.swing.JButton btn_paiement_fact;
    private javax.swing.JButton btn_quit;
    private javax.swing.JButton btn_visualiser_art;
    private javax.swing.JButton btn_voir_facture;
    private org.jdesktop.swingx.JXDatePicker dateDebut;
    private org.jdesktop.swingx.JXDatePicker dateFin;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable liste_articles;
    private javax.swing.JScrollPane liste_facture;
    private javax.swing.JTable liste_factures;
    // End of variables declaration//GEN-END:variables
}
